software-mansion/scarb

.cargo/config.toml, .github/workflows/release.yml
=> Release workflow

README.md, scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/init.rs, scarb/src/bin/scarb/commands/mod.rs, scarb/src/bin/scarb/commands/new.rs, scarb/src/core/config.rs, scarb/src/core/manifest/mod.rs, scarb/src/core/mod.rs, scarb/src/core/package/mod.rs, scarb/src/internal/fsx.rs, scarb/src/lib.rs, scarb/src/ops/manifest.rs, scarb/src/ops/mod.rs, scarb/src/ops/new.rs, scarb/src/sources/path.rs, scarb/tests/new_and_init.rs
=> Add `scarb new` and `scarb init` commands, getting started in README

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/init.rs, scarb/src/core/config.rs, scarb/src/core/manifest/toml.rs, scarb/src/core/package/mod.rs, scarb/src/core/registry/download_depot.rs, scarb/src/core/registry/mod.rs, scarb/src/core/source/id.rs, scarb/src/core/workspace.rs, scarb/src/dirs.rs, scarb/src/internal/fsx.rs, scarb/src/metadata/mod.rs, scarb/src/ops/compile.rs, scarb/src/ops/manifest.rs, scarb/src/ops/new.rs, scarb/src/ops/resolve.rs, scarb/src/ops/workspace.rs, scarb/tests/e2e/new_and_init.rs, scarb/tests/e2e/support/fsx.rs, scarb/tests/e2e/support/mod.rs
=> Enforce UTF-8 in user-provided paths

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/build.rs, scarb/src/bin/scarb/commands/commands.rs, scarb/src/bin/scarb/commands/init.rs, scarb/src/bin/scarb/commands/manifest_path.rs, scarb/src/bin/scarb/commands/metadata.rs, scarb/src/bin/scarb/commands/new.rs, scarb/src/bin/scarb/main.rs, scarb/src/core/config.rs, scarb/src/lib.rs, scarb/src/ops/compile.rs, scarb/src/ui/machine.rs, scarb/src/ui/message.rs, scarb/src/ui/mod.rs, scarb/src/ui/typed.rs, scarb/src/ui/value.rs, scarb/tests/e2e/build.rs, scarb/tests/e2e/manifest_path.rs, scarb/tests/e2e/metadata.rs
=> User interface

scarb/Cargo.toml, scarb/build.rs, scarb/src/bin/scarb/args.rs, scarb/src/lib.rs, scarb/src/version.rs
=> Include information what Cairo version is bundled in --version output

.github/workflows/release.yml, ci/verify-release.sh, scarb/build.rs
=> Fix issues blocking from publishing to crates.io

ARCHITECTURE.md, README.md
=> Add some more documentation pieces

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/commands.rs, scarb/src/lib.rs, scarb/src/ops/subcommands.rs, scarb/src/process.rs, scarb/tests/e2e/subcommand.rs
=> Allow listing installed subcommands

scarb/src/compiler/profile.rs, scarb/src/metadata/mod.rs, scarb/tests/e2e/metadata.rs
=> Add compilation units to metadata

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/core/manifest/mod.rs, scarb/src/core/registry/cache.rs, scarb/src/core/registry/mod.rs, scarb/src/core/registry/source_map.rs, scarb/src/core/source/id.rs, scarb/src/internal/async_cache.rs, scarb/src/internal/cloneable_error.rs, scarb/src/internal/mod.rs
=> Implement registry caching

scarb/build.rs
=> Skip downloading corelib for docs.rs

scarb/src/bin/scarb/commands/fmt.rs, scarb/src/bin/scarb/errors.rs, scarb/src/bin/scarb/main.rs
=> Move exit code handling to error types system

scarb/src/ops/new.rs, scarb/tests/e2e/new_and_init.rs
=> Pass absolute path to read workspace on Scarb new

scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/tests/e2e/metadata.rs
=> Add tool metadata to manifest

Cargo.lock, Cargo.toml
=> Update Cairo to 1.0.0-alpha.4

website/pages/docs/reference/manifest.mdx
=> Add tool section to docs

Cargo.lock, Cargo.toml, scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/ops/new.rs, scarb/tests/e2e/build.rs, scarb/tests/e2e/build_starknet_contract.rs, scarb/tests/e2e/build_targets.rs, scarb/tests/e2e/fmt.rs, scarb/tests/e2e/git_source.rs, scarb/tests/e2e/metadata.rs, scarb/tests/e2e/resolver_with_git.rs, scarb/tests/e2e/support/manifest_edit.rs, scarb/tests/e2e/support/project_builder.rs, website/pages/docs/guides/creating-a-new-package.mdx, website/pages/docs/guides/dependencies.mdx, website/pages/docs/reference/manifest.mdx
=> Update Cairo to `1.0.0-alpha.6`

Cargo.lock, scarb-metadata/Cargo.toml, scarb-metadata/src/command.rs, scarb-metadata/src/lib.rs, scarb-metadata/tests/command.rs, scarb/Cargo.toml, scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/compilers/lib.rs, scarb/src/compiler/compilers/starknet_contract.rs, scarb/src/compiler/helpers.rs, scarb/src/compiler/repository.rs, scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/target.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/mod.rs, scarb/src/core/package/id.rs, scarb/src/core/package/mod.rs, scarb/src/core/registry/mod.rs, scarb/src/core/source/id.rs, scarb/src/internal/stable_hash.rs, scarb/src/lib.rs, scarb/src/ops/compile.rs, scarb/src/ops/metadata.rs, scarb/src/ops/new.rs, scarb/src/ops/resolve.rs, scarb/tests/e2e/build_starknet_contract.rs
=> Stabilize metadata format and fix all problems found

MAINTAINING.md
=> Write MAINTAINING.md

Cargo.lock, Cargo.toml, scarb/src/compiler/compilers/lib.rs, scarb/tests/e2e/build_starknet_contract.rs
=> Enable `StarknetPlugin` on `lib` targets

.github/workflows/ci.yml, .github/workflows/release.yml, scarb/tests/e2e/flock.rs
=> Fix recent CI issues

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/compilers/lib.rs, scarb/src/compiler/compilers/starknet_contract.rs, scarb/src/compiler/db.rs, scarb/src/compiler/helpers.rs, scarb/src/compiler/mod.rs, scarb/src/compiler/plugin/builtin.rs, scarb/src/compiler/plugin/mod.rs, scarb/src/compiler/repository.rs, scarb/src/core/config.rs, scarb/src/core/manifest/target.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/package/id.rs, scarb/src/core/package/mod.rs, scarb/src/core/package/name.rs, scarb/src/core/registry/cache.rs, scarb/src/core/resolver.rs, scarb/src/core/source/id.rs, scarb/src/ops/compile.rs, scarb/src/ops/resolve.rs, scarb/src/resolver/mod.rs, scarb/src/sources/git/canonical_url.rs, scarb/tests/e2e/build_targets.rs
=> Prepare for compiler plugins packages

Cargo.lock, Cargo.toml
=> Update Cairo to `1.0.0-rc0`

website/pages/docs/guides/using-scarb-in-ci.mdx
=> Add scarb ci examples for circleci and gitlabci

scarb/src/core/package/name.rs, website/pages/docs/reference/manifest.mdx
https://github.com/software-mansion/scarb/pull/296#pullrequestreview-1412973251
=> Remove invalid sentence that package names cannot start with `_`

website/components/mermaid.tsx, website/package-lock.json, website/package.json, website/pages/docs/reference/compilation-model.mdx
=> Compilation Model docs

website/pages/download.mdx
=> Fix download tables scrolling

website/pages/docs/guides/using-scarb-in-ci.mdx
=> Docs: Use Scarb installer in CI workflows example

scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/ops/resolve.rs, scarb/tests/e2e/build.rs, scarb/tests/e2e/support/project_builder.rs
Adding `cairo-version` to `Scarb.toml` and comparing it with current cairo version
Closes #226
=> Add cairo-version to Scarb.toml and comparing it with current cairo version

scarb/src/core/manifest/toml_manifest.rs, scarb/src/ops/resolve.rs
commit-id:a9aebfae
---
**Stack**:
- #345
- #344
- #343
- #346
- #342
- #341
- #340
- #339 ⬅
- #338
=> Minor imports reformat

scarb/src/core/manifest/toml_manifest.rs
commit-id:7e15b5ed
---
**Stack**:
- #345
- #344
- #343
- #346
- #342
- #341
- #340 ⬅
- #339
- #338
=> Reorder code

scarb/src/core/manifest/compiler_config.rs, scarb/src/core/manifest/dependency.rs, scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/summary.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/registry/mod.rs, scarb/src/core/registry/patch_map.rs, scarb/src/core/registry/patcher.rs, scarb/src/ops/resolve.rs, scarb/src/resolver/mod.rs, scarb/tests/e2e/build_cairo_plugin.rs, scarb/tests/e2e/main.rs, scarb/tests/e2e/resolver_with_git.rs
commit-id:289e98b3
---
**Stack**:
- #358
- #357
- #350
- #356
- #355 ⬅
- #354
- #353
- #352
=> Parse `[cairo-plugin]` in `Scarb.toml`

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/summary.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/registry/mod.rs
commit-id:8d953e5b
---
**Stack**:
- #363
- #361
- #357
- #360 ⬅
- #359
=> Create `ManifestBuilder` and move checks inside

Cargo.lock, Cargo.toml, examples/hello_world/src/lib.cairo, examples/starknet_hello_world/cairo_project.toml, examples/starknet_hello_world/src/lib.cairo, extensions/scarb-cairo-test/Cargo.toml, extensions/scarb-cairo-test/src/main.rs, extensions/scarb-cairo-test/tests/examples.rs, scarb/Cargo.toml, scarb/build.rs, scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/external.rs, scarb/src/bin/scarb/commands/mod.rs, scarb/src/bin/scarb/commands/run.rs, scarb/src/bin/scarb/commands/test.rs, scarb/src/bin/scarb/main.rs, scarb/src/core/errors.rs, scarb/src/core/mod.rs, scarb/src/ops/scripts.rs, scarb/src/ops/subcommands.rs, scarb/tests/e2e/main.rs, scarb/tests/e2e/support/command.rs, scarb/tests/e2e/test.rs, website/pages/docs/_meta.json, website/pages/docs/guides/defining-custom-profiles.mdx, website/pages/docs/guides/defining-custom-scripts.mdx, website/pages/docs/testing.mdx
=> Scarb Test Runner 🚀

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/internal/stable_hash.rs, scarb/src/sources/git/canonical_url.rs
=> Replace deprecated Rust's SipHasher with XXH3

scarb/src/ui/mod.rs
https://doc.rust-lang.org/std/default/trait.Default.html#enums
=> Replace manual Default impls with derive for UI enums

scarb/src/ops/compile.rs
The Cairo compiler tends to consume too much stack space in some specific cases: https://github.com/starkware-libs/cairo/issues/3530. It does not seem to consume infinite amounts though, so we try to confine it in arbitrarily chosen big memory chunk.
**This change should be reverted when Cairo fixes their issue upstream.**
fix #429
=> Run compiler in a new thread with increased stack size

Cargo.lock, Cargo.toml, examples/cairo_run_example/README.md, examples/cairo_run_example/Scarb.toml, examples/cairo_run_example/src/lib.cairo, extensions/scarb-cairo-language-server/Cargo.toml, extensions/scarb-cairo-run/Cargo.toml, extensions/scarb-cairo-run/src/main.rs, extensions/scarb-cairo-run/tests/examples.rs, extensions/scarb-cairo-test/Cargo.toml, install.sh, scarb-metadata/Cargo.toml, scarb/Cargo.toml, scarb/build.rs, scarb/src/ops/compile.rs, scarb/src/subcommands.rs, scarb/tests/e2e/subcommand.rs, utils/create-output-dir/Cargo.toml, utils/test-for-each-example/Cargo.toml, website/package-lock.json, website/package.json, website/pages/docs/_meta.json, website/pages/docs/cairo-run.mdx, website/pages/docs/extensions/subcommands.mdx, website/pages/docs/install.mdx
=> Backport features to release 0.4

scarb/src/resolver/mod.rs
commit-id:70a01729
---
**Stack**:
- #447
- #446
- #445
- #444
- #443
- #441 ⬅
=> Resolver: add all dependencies to graph

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, extensions/scarb-cairo-run/Cargo.toml, extensions/scarb-cairo-run/tests/examples.rs, scarb/tests/examples.rs, scarb/tests/subcommand.rs, utils/scarb-test-support/src/cargo.rs, utils/scarb-test-support/src/command.rs, utils/scarb-test-support/src/lib.rs
=> Partition tests using nextest

.github/workflows/ci.yml
The Windows side of things is significantly lower, and I have ideas how to further improve times on Linux machines.
---
**Stack**:
- #475
- #474
- #473 ⬅
=> Make CI workflow run on Linux only

website/pages/download/index.mdx
=> Temporarily remove `asdf plugin add scarb` until it will work

website/pages/docs/guides/using-scarb-in-ci.mdx
1. Use setup action
2. Focus on CI workflow
=> Update CI docs page

scarb/src/process.rs
commit-id:e0d74a40
---
**Stack**:
- #465
- #446
- #447
- #445
- #444 ⬅
=> Add file is_hidden check

Cargo.lock, Cargo.toml, examples/hello_workspaces/README.md, examples/hello_workspaces/Scarb.toml, examples/hello_workspaces/crates/addition/Scarb.toml, examples/hello_workspaces/crates/addition/src/lib.cairo, examples/hello_workspaces/crates/fibonacci/Scarb.toml, examples/hello_workspaces/crates/fibonacci/src/lib.cairo, examples/hello_workspaces/src/lib.cairo, scarb/Cargo.toml, scarb/src/core/manifest/maybe_workspace.rs, scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/scripts.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/package/mod.rs, scarb/src/core/workspace.rs, scarb/src/ops/manifest.rs, scarb/src/ops/scripts.rs, scarb/src/ops/workspace.rs, scarb/src/sources/path.rs, scarb/tests/build.rs, scarb/tests/metadata.rs, scarb/tests/profiles.rs, utils/scarb-test-support/src/lib.rs, utils/scarb-test-support/src/project_builder.rs, utils/scarb-test-support/src/workspace_builder.rs
commit-id:214ce15e
---
**Stack**:
- #508
- #506
- #502
- #500
- #490
- #489
- #465
- #446 ⬅
- #447
- #445
=> Add workspace example

scarb-metadata/src/command.rs, scarb-metadata/src/lib.rs, scarb-metadata/src/packages_filter.rs, scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/build.rs, scarb/src/bin/scarb/commands/external.rs, scarb/src/bin/scarb/commands/fmt.rs, scarb/src/bin/scarb/commands/mod.rs, scarb/src/bin/scarb/commands/run.rs, scarb/src/bin/scarb/commands/test.rs, scarb/src/core/package/mod.rs, scarb/src/core/workspace.rs, scarb/src/ops/compile.rs, scarb/src/ops/fmt.rs, scarb/src/ops/metadata.rs, scarb/src/ops/scripts.rs, scarb/src/ops/subcommands.rs, scarb/src/subcommands.rs, scarb/tests/fmt.rs, scarb/tests/test_subcommand.rs
commit-id:d17e0f4a
---
**Stack**:
- #508
- #506
- #502
- #500
- #490 ⬅
- #489
- #465
=> Format only selected packages

scarb/tests/build_starknet_contract.rs, scarb/tests/build_starknet_external_contracts.rs
https://github.com/software-mansion/scarb/actions/runs/5697461654/job/15444219731
=> Make build tests not fail if they run too long

scarb/src/resolver/mod.rs, scarb/tests/git_source.rs, scarb/tests/metadata.rs, scarb/tests/profiles.rs, utils/scarb-test-support/src/command.rs
=> Patch path dependencies for git sources

scarb/src/sources/standard_lib.rs
=> Add runtime check for Core library and Cairo compiler versions

scarb/Cargo.toml, scarb/build.rs
=> Add compile time check for Core library and Cairo compiler versions

.github/workflows/nightly.yml, .github/workflows/release.yml, Cargo.lock, xtask/Cargo.toml, xtask/src/main.rs, xtask/src/nightly_release_notes.rs
=> Publish nightlies to release repository

README.md, website/pages/docs/reference/manifest.mdx, website/pages/docs/reference/workspaces.mdx, website/pages/docs/starknet/contract-target.mdx
=> Workspace documentation

scarb/src/ops/compile.rs
Reverts software-mansion/scarb#432
=> Revert "Run compiler in a new thread with increased stack size"

MAINTAINING.md
=> MAINTAINING.md: stop publishing `scarb` crate to crates.io

extensions/scarb-cairo-run/src/main.rs, extensions/scarb-cairo-run/tests/examples.rs, scarb-metadata/src/command/internal_command.rs, scarb-metadata/src/command/metadata_command.rs, scarb-metadata/src/command/mod.rs, scarb-metadata/src/command/scarb_command.rs, scarb-metadata/src/lib.rs, scarb-metadata/tests/scarb_command.rs
=> Add Scarb command abstraction, build Scarb project before run

examples/hello_world/Scarb.toml, examples/hello_world/src/lib.cairo, scarb/src/bin/scarb/args.rs, website/.vitepress/components/home/Terminal.vue, website/docs/cheatsheet.md, website/docs/guides/dependencies.md, website/docs/guides/working-on-an-existing-package.md, website/docs/reference/specifying-dependencies.md, website/docs/reference/workspaces.md
=> Update Alexandria references to refer to new package structure

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/cache_clean.rs, scarb/src/bin/scarb/commands/mod.rs, scarb/src/ops/cache.rs, scarb/src/ops/mod.rs, scarb/tests/cache.rs
=> Add scarb cache clean subcommand

.github/workflows/website-deploy.yml
=> Make Website Deploy workflow always deploy from main when run on release event

extensions/scarb-cairo-run/src/main.rs
https://github.com/starkware-libs/cairo/pull/3738
=> Fix error message for missing gas

README.md, install.sh, website/download.md
=> Add support for installing nightlies in install script

Cargo.lock, Cargo.toml, scarb/Cargo.toml
**Stack**:
- #582
- #581
- #580 ⬅
=> Remove unused `tracing-futures` dependency

scarb/tests/scripts.rs, scarb/tests/subcommand.rs, scarb/tests/test_subcommand.rs, utils/scarb-test-support/src/filesystem.rs
=> Refactor write_script duplication in tests

extensions/scarb-cairo-test/src/main.rs
commit-id:c5930f7e
---
**Stack**:
- #597
- #596
- #595
- #594 ⬅
=> Test-runner: add unit components to compilation

scarb-metadata/src/command/metadata_command.rs, scarb/src/bin/scarb/commands/commands.rs, scarb/src/compiler/compilers/starknet_contract.rs, scarb/src/compiler/profile.rs, scarb/src/core/manifest/mod.rs, scarb/src/core/package/id.rs, scarb/src/manifest_editor/dep_id.rs, utils/scarb-test-support/src/workspace_builder.rs, utils/scarb-ui/src/verbosity.rs
commit-id:f621139c
---
**Stack**:
- #615
- #614
- #597
- #612
- #611
- #596
- #595
- #613 ⬅
=> Fix formatting / clippy warning for 1.72

scarb/src/compiler/db.rs, scarb/src/compiler/plugin/builtin.rs, scarb/src/compiler/plugin/mod.rs
=> Make inline plugins loadable via CairoPluginRepository

scarb/tests/build.rs, scarb/tests/build_cairo_plugin.rs, scarb/tests/build_starknet_contract.rs, scarb/tests/build_starknet_contract_allowed_libfuncs.rs, scarb/tests/build_starknet_external_contracts.rs, scarb/tests/build_targets.rs, scarb/tests/flock.rs, scarb/tests/git_source.rs, scarb/tests/git_source_network.rs, scarb/tests/resolver_with_git.rs
=> Reduce number of scarb build calls in tests

website/.vitepress/components/Footer.vue, website/.vitepress/components/Snippet.vue, website/.vitepress/components/home/Download.vue, website/.vitepress/components/home/Features.vue, website/.vitepress/components/home/Terminal.vue, website/.vitepress/theme/style.css, website/package-lock.json, website/package.json
Lots of styling stuff has been changed. Please run the website locally and verify everything looks OK.
=> Upgrade Vitepress

scarb/src/compiler/compilers/mod.rs, scarb/src/compiler/compilers/test.rs, scarb/src/compiler/repository.rs, scarb/src/core/manifest/toml_manifest.rs
commit-id:e04ca939
---
**Stack**:
- #630
- #629
- #628
- #627
- #626
- #615
- #614
- #597
- #612
- #611
- #596 ⬅
=> Add [[test]] target definition

scarb/src/core/package/name.rs, scarb/src/resolver/mod.rs, scarb/tests/new_and_init.rs, website/docs/reference/manifest.md
=> Disallow uppercase letters in package name

scarb/src/compiler/compilers/lib.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/tests/build_starknet_contract.rs, scarb/tests/build_targets.rs, website/docs/reference/targets.md
=> Add textual Sierra artifact support

.github/workflows/_check-release.yml
=> Run check release tests with ci profile

scarb/src/compiler/compilers/starknet_contract.rs, scarb/tests/build_starknet_external_contracts.rs
solve #577 
only one test added, do we need to test more complex path declarations?
=> Implement wild card contracts selector

scarb/src/core/manifest/dependency.rs, scarb/src/core/manifest/summary.rs, scarb/src/core/manifest/target.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/registry/mod.rs, scarb/src/ops/resolve.rs, scarb/src/resolver/mod.rs
commit-id:1aba1429
---
**Stack**:
- #651
- #650
- #649
- #629
- #628
- #626
- #627
- #615
- #597
- #612
- #611 ⬅
=> Add target kind info to manifest dependency

scarb/src/bin/scarb/args.rs
commit-id:f16ef4f2
---
**Stack**:
- #679
- #651
- #649
- #628
- #660
- #615
- #597
- #659
- #612
- #678 ⬅
=> Read scarb profile argument from env

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/bin/scarb/args.rs, scarb/src/core/resolver.rs, scarb/src/resolver/mod.rs
commit-id:ade97ea3
---
**Stack**:
- #679
- #651
- #649
- #628
- #660
- #615
- #597
- #659
- #612 ⬅
=> Build dependency resolution with target_kind filter

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/bin/scarb/args.rs, scarb/src/core/manifest/summary.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/registry/mod.rs, scarb/src/core/resolver.rs, scarb/src/resolver/mod.rs
commit-id:04d393f0
---
**Stack**:
- #679
- #651
- #649
- #628
- #660
- #615
- #597
- #659 ⬅
=> Store target kinds on manifest summary

scarb/tests/clean.rs, scarb/tests/metadata.rs
https://github.com/software-mansion/scarb/actions/runs/6242382328/job/16946248521
=> Fix tests assertions for non-Unix platforms

.github/workflows/nightly.yml
=> Notify on nightly fail

scarb/src/core/manifest/scripts.rs, scarb/src/ops/scripts.rs, utils/scarb-ui/src/lib.rs
=> Fix colours in subcommands

Cargo.lock, scarb/Cargo.toml, scarb/scarblib/test_plugin/Scarb.toml, scarb/src/compiler/plugin/builtin.rs, scarb/src/compiler/plugin/mod.rs, scarb/src/core/manifest/summary.rs, scarb/src/core/manifest/target.rs, scarb/src/core/package/id.rs, scarb/src/core/package/name.rs, scarb/src/core/registry/mod.rs, scarb/src/ops/compile.rs, scarb/src/ops/resolve.rs, scarb/src/resolver/mod.rs, scarb/tests/metadata.rs
commit-id:ae5578cd
---
**Stack**:
- #688
- #679
- #651
- #649
- #628
- #660
- #615
- #597 ⬅
=> Add test compilation unit component for integration test targets

scarb/src/core/resolver.rs, scarb/src/ops/resolve.rs, scarb/src/resolver/mod.rs
commit-id:75463384
---
**Stack**:
- #688
- #679
- #651
- #649
- #628
- #660
- #615 ⬅
=> Use ws solution per target kind

extensions/scarb-cairo-test/src/main.rs, scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/build.rs, scarb/src/ops/compile.rs, scarb/tests/build_targets.rs
commit-id:a71d73f9
---
**Stack**:
- #688
- #679
- #651
- #649 ⬅
=> Skip test target compilation without --test flag

scarb/src/core/manifest/target.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/ops/resolve.rs
commit-id:154efeed
---
**Stack**:
- #706
- #688
- #679 ⬅
=> Add test type prop on test targets

scarb/src/core/manifest/toml_manifest.rs, scarb/tests/build_targets.rs
commit-id:a8189b32
---
**Stack**:
- #706
- #688 ⬅
=> Compile lib-style integration tests

scarb/src/internal/restricted_names.rs
=> Update internal restricted package names

scarb/src/core/manifest/toml_manifest.rs
**Stack**:
- #709
- #697
- #675
- #657
- #646
- #708
- #707 ⬅
=> Use UTF-8 paths for `source-path` field

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/core/package/id.rs, scarb/src/internal/fsx.rs, scarb/src/ops/package.rs, scarb/tests/package.rs
**Stack**:
- #697
- #710
- #726
- #675 ⬅
=> Create actual .tar.zst archive

utils/scarb-ui/src/args/packages_filter.rs
commit-id:c4ba78ac
---
**Stack**:
- #727
- #723
- #722
- #721 ⬅
=> Allow passing packages filter with env var

utils/scarb-ui/src/args/packages_filter.rs
commit-id:d571a145
---
**Stack**:
- #727
- #723
- #722 ⬅
=> Build packages filter

scarb/tests/scripts.rs, utils/scarb-ui/src/args/packages_filter.rs
=> Add more packages filter tests

scarb/src/core/source/id.rs, scarb/src/sources/git/client.rs, scarb/src/sources/git/mod.rs, scarb/tests/resolver_with_git.rs
commit-id:557f1ffa
---
**Stack**:
- #745
- #744
- #743 ⬅
=> Write actual git revision for git source ids

utils/scarb-ui/src/components/typed.rs
**Stack**:
- #753
- #752
- #751
- #750 ⬅
=> Remove dead code in `scarb-ui`

utils/scarb-ui/src/args/packages_filter.rs, utils/scarb-ui/src/lib.rs
**Stack**:
- #753
- #752
- #751 ⬅
=> Fix Clippy `rust_2018_idioms` in `scarb-ui`

utils/scarb-ui/src/args/mod.rs, utils/scarb-ui/src/components/machine.rs, utils/scarb-ui/src/components/mod.rs, utils/scarb-ui/src/components/spinner.rs, utils/scarb-ui/src/components/status.rs, utils/scarb-ui/src/components/typed.rs, utils/scarb-ui/src/components/value.rs, utils/scarb-ui/src/lib.rs, utils/scarb-ui/src/message.rs, utils/scarb-ui/src/verbosity.rs, utils/scarb-ui/src/widget.rs
=> Document entirety of `scarb-ui`

.github/workflows/nightly.yml, xtask/src/set_scarb_version.rs
=> Ignore version pre-release part in nightlies

scarb/src/compiler/compilers/lib.rs, scarb/src/compiler/helpers.rs
commit-id:a0d535c6
---
**Stack**:
- #759
- #761 ⬅
=> Use BufWriter for JSON serialized output files

scarb/src/compiler/compilers/lib.rs, scarb/src/compiler/compilers/test.rs
=> Add tracing span for test compilation

scarb/src/core/source/id.rs
commit-id:195ce7f6
---
**Stack**:
- #763
- #745
- #744
- #762 ⬅
=> Parse precise part from pretty url

scarb/src/core/publishing/mod.rs, scarb/src/core/publishing/source.rs, scarb/src/ops/package.rs, scarb/tests/package.rs, utils/scarb-test-support/src/gitx.rs
**Stack**:
- #758
- #757
- #748
- #746
- #733
- #697
- #732 ⬅
=> Implement package source files collection

scarb/src/core/publishing/source.rs, scarb/src/lib.rs, scarb/tests/package.rs, utils/scarb-test-support/src/project_builder.rs
**Stack**:
- #758
- #757
- #748
- #746
- #733 ⬅
=> Do not include Scarb.lock in packages

scarb/src/core/publishing/manifest_normalization.rs, scarb/src/core/source/id.rs
**Stack**:
- #767
- #768
- #758 ⬅
=> Replace several TODO comments with `todo!` calls in packaging logic

scarb/src/ops/package.rs, scarb/tests/package.rs, utils/scarb-test-support/src/fsx.rs
=> Fix package op issues on Windows

scarb/src/sources/git/client.rs
commit-id:48d35381
---
**Stack**:
- #781
- #780
- #779
- #778
- #777
- #775 ⬅
=> Ensure git checkout returns existing revision

scarb/src/flock.rs, scarb/src/internal/lazy_directory_creator.rs, scarb/src/sources/git/mod.rs, scarb/src/sources/standard_lib.rs
**Stack**:
- #783
- #767
- #782 ⬅
=> Add `Filesystem::into_child` method for easier chaining

scarb/src/flock.rs, scarb/src/sources/standard_lib.rs
**Stack**:
- #783
- #767
- #787 ⬅
=> Extract `protected_run_if_not_ok!` macro

scarb/src/ops/package.rs
**Stack**:
- #790
- #783
- #767
- #789 ⬅
=> Add tracing instrumentation to package ops

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/core/checksum.rs, scarb/src/core/mod.rs, scarb/src/core/registry/index/record.rs
**Stack**:
- #793
- #790
- #792
- #783 ⬅
=> Implement `Checksum` and `Digest` mechanisms

scarb/src/core/registry/mod.rs, scarb/src/resolver/mod.rs
commit-id:80d6f606
---
**Stack**:
- #781
- #800
- #780 ⬅
=> Implement lockfile tests

Cargo.lock, Cargo.toml, utils/scarb-test-support/Cargo.toml, utils/scarb-test-support/src/lib.rs, utils/scarb-test-support/src/main.rs, utils/scarb-test-support/src/simple_http_server.rs
**Stack**:
- #819
- #818
- #809
- #808
- #807
- #806
- #805
- #803
- #802
- #799 ⬅
=> Implement simple http server for testing HTTP registries

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/core/config.rs
**Stack**:
- #819
- #818
- #809
- #808
- #807
- #806
- #805
- #803
- #802 ⬅
=> Set up `reqwest` HTTP client

website/docs/guides/formatting.md
commit-id:e79b931d
---
**Stack**:
- #830
- #829
- #836 ⬅
=> Docs: Use kebab-case for formatting options

scarb/src/core/publishing/manifest_normalization.rs, scarb/tests/package.rs
**Stack**:
- #819
- #818
- #809
- #808
- #807
- #806
- #805 ⬅
=> Expand registry specification to registry URL when packaging

README.md, website/docs/cheatsheet.md, website/docs/reference/lockfile.md
=> Add scarb update docs

Cargo.lock, Cargo.toml, scarb/Cargo.toml
commit-id:01e6ae9b
---
**Stack**:
- #852
- #851 ⬅
=> Use rustls-tls with native roots on unix targets

.github/workflows/nightly.yml
=> Add dry_run arg to nightly workflow

website/docs/extensions/testing.md, website/docs/reference/targets.md
=> Add test targets docs

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/package.rs, scarb/src/bin/scarb/commands/publish.rs, scarb/src/lib.rs, scarb/src/ops/package.rs, scarb/src/ops/publish.rs, scarb/src/sources/git/client.rs, scarb/src/sources/git/mod.rs, scarb/tests/package.rs
=> Prevent packaging with uncommited Git changes

Cargo.lock, Cargo.toml
- `deno_task_shell`
- ran `cargo update`
=> Major dependencies update

scarb/tests/package.rs
commit-id:c311ea20
---
**Stack**:
- #875
- #874 ⬅
=> Add note about symlinks tests on windows

examples/hello_world/Scarb.toml, scarb/src/core/manifest/mod.rs, scarb/src/ops/metadata.rs, scarb/src/ops/new.rs
=> Write edition to manifest on scarb new

scarb/src/core/manifest/toml_manifest.rs, scarb/src/lib.rs, scarb/src/ops/new.rs, scarb/src/ops/resolve.rs
commit-id:18fc4713
---
**Stack**:
- #884
- #885 ⬅
=> Fix source path display on windows

scarb/tests/local_registry.rs
=> Ignore tests failing as of #883

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/tests/http_registry.rs, utils/scarb-test-support/src/main.rs, utils/scarb-test-support/src/registry/http.rs, utils/scarb-test-support/src/simple_http_server.rs
---
**Stack**:
- #892
- #846
- #845
- #844
- #819
- #818 ⬅
=> Set up machinery for testing HTTP interactions of HTTP registry

utils/scarb-ui/src/args/packages_filter.rs
=> Add PackagesFilterLong without short clap arguments

scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/publishing/manifest_normalization.rs, scarb/src/core/publishing/source.rs, scarb/src/lib.rs, scarb/src/ops/metadata.rs, scarb/src/ops/package.rs, scarb/tests/metadata.rs, scarb/tests/package.rs
=> Handle readme and license files in scarb package

Cargo.lock, Cargo.toml, scarb/tests/build.rs, scarb/tests/build_starknet_contract.rs
Fixes tests in https://github.com/software-mansion/scarb/actions/runs/6910525403
=> Fix failing tests by adjusting stderr message assertions

scarb/src/core/checksum.rs, scarb/src/core/manifest/dependency.rs, scarb/src/core/registry/client/cache.rs, scarb/src/sources/registry.rs, scarb/tests/registry_checksums.rs
fix #834
---
**Stack**:
- #912
- #911
- #910
- #909
- #906 ⬅
=> Handle checksums in registry packages

scarb/src/core/manifest/summary.rs, scarb/src/core/package/mod.rs, scarb/src/core/registry/client/cache.rs, scarb/src/sources/registry.rs
**Stack**:
- #912
- #911
- #910 ⬅
=> Store package checksum in `Summary`

scarb/src/resolver/mod.rs
=> Remove obsolete TODO comment

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/package.rs, scarb/src/bin/scarb/commands/publish.rs, scarb/src/core/registry/package_source_store.rs, scarb/src/flock.rs, scarb/src/ops/package.rs, scarb/src/ops/publish.rs, scarb/tests/local_registry.rs, scarb/tests/package.rs
=> Verify that package tarball compiles

scarb/src/ops/scripts.rs, scarb/src/ops/subcommands.rs, scarb/tests/scripts.rs
Resolves #925 
Mimic https://github.com/denoland/deno/blob/e3e51313f6059829fc5eeaafe040b00ba9f15154/cli/tools/task.rs#L200
=> Pass env variables to scripts shell

scarb/src/compiler/helpers.rs, scarb/src/core/manifest/compiler_config.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/tests/build.rs, scarb/tests/examples.rs, website/docs/reference/manifest.md
commit-id:8d185ce7
---
**Stack**:
- #952
- #951 ⬅
=> Add allow_warnings to compiler config

scarb/src/compiler/compilers/test.rs
=> Remove DiagnosticReporter creation duplicate

scarb/tests/http_registry.rs, utils/scarb-test-support/src/registry/http.rs, utils/scarb-test-support/src/registry/local.rs
=> Add test for verified HttpRegistry publish

scarb/src/core/source/id.rs
=> Use `cannonical_url` instead of `url` for SourceId comparisons

scarb/tests/fmt.rs
commit-id:22a68ba9
---
**Stack**:
- #971
- #970
- #967
- #966
- #965 ⬅
=> Add fmt parsing error test case

scarb/src/manifest_editor/add.rs, scarb/tests/add.rs
commit-id:d8d2f542
formatting
better validation, test added
=> validate git urls

Cargo.lock, Cargo.toml, extensions/scarb-snforge-test-collector/src/metadata.rs, scarb/src/compiler/db.rs
Fixes nightlies: https://github.com/software-mansion/scarb/actions/runs/7108434843/job/19351728297
Change needed due to cairo([#4496](https://github.com/starkware-libs/cairo/commit/6e3f32e1d0aacca12c62e976c7dee3316798b358))
=> Use `CrateSettings` instead of `SingleCrateConfig`

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/compiler/helpers.rs, scarb/tests/build.rs, scarb/tests/build_starknet_contract.rs, scarb/tests/build_targets.rs, scarb/tests/package.rs
commit-id:ed123aeb
---
**Stack**:
- #971
- #970
- #967 ⬅
=> Use severity aware diagnostic callback

extensions/scarb-cairo-run/src/main.rs, extensions/scarb-cairo-run/tests/examples.rs, website/docs/extensions/cairo-run.md
=> Update cairo-run docs, add no-build argument

scarb/src/core/manifest/toml_manifest.rs, scarb/tests/build_targets.rs
=> Ignore non-cairo files in integration tests auto-detect

scarb/src/ops/resolve.rs, scarb/tests/build.rs
commit-id:4ee3dbc4
Co-authored-by: Berzan <berzan@tutanota.com>
=> Make error msg easier to understand

extensions/scarb-snforge-test-collector/src/compilation/test_collector.rs, extensions/scarb-snforge-test-collector/src/compilation/test_collector/config.rs, extensions/scarb-snforge-test-collector/src/compilation/test_collector/plugin.rs
This reverts commit ca136d08723950fe2131bf476a8ecf2757a01211.
=> Revert "adds max steps attribute (#979)"

.github/workflows/_build-release.yml, .github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/website-deploy.yml
- `actions/download-artifact@v3` -> `v4`
- `actions/upload-artifact@v3` -> `v4`
- `actions/configure-pages@v3` -> `v4`
- `actions/upload-pages-artifact@v2` -> `v3`
- `actions/deploy-pages@v2` -> `v4`
=> Update artifacts and pages actions

scarb/tests/metadata.rs
commit-id:001f9da5
---
**Stack**:
- #1007
- #1030 ⬅
=> Add ignored test case for dev-deps propagation

scarb/src/bin/scarb/args.rs, scarb/tests/scripts.rs
- Added version and author information.
- Added a sentence about -h/--help difference.
- Added links to useful resources online.
=> Expand help message preface

scarb/tests/build.rs
=> Fix ignored test

scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/db.rs, scarb/tests/build.rs, utils/scarb-test-support/src/command.rs
commit-id:5a5989db
---
**Stack**:
- #1100
- #1110
- #1093
- #1092
- #1091
- #1060
- #1059
- #1112 ⬅
=> Allow compilation of packages with `no-core` flag enabled.

scarb/scarblib/starknet/Scarb.toml, scarb/scarblib/test_plugin/Scarb.toml, scarb/src/compiler/compilation_unit.rs, scarb/src/ops/resolve.rs
commit-id:350fe920
---
**Stack**:
- #1100
- #1110
- #1093
- #1092
- #1091
- #1060
- #1059 ⬅
=> Add builtin prop on cairo plugin target definition

scarb-metadata/CHANGELOG.md, scarb-metadata/src/lib.rs
commit-id:0b332dae
---
**Stack**:
- #1119
- #1118 ⬅
=> Fix experimental_features deserialization backward compatibility

.github/workflows/ci.yml, scarb-metadata/tests/command.rs, scarb-metadata/tests/scarb_command.rs
=> Check backward compatibility of metadata command deserialization

extensions/scarb-snforge-test-collector/src/metadata.rs, extensions/scarb-snforge-test-collector/tests/test.rs
Stop compiling items under `#[cfg(test)]` defined in dependencies.
=> Set crate-level cfg_set in snforge-test-collector

Cargo.lock, Cargo.toml, plugins/scarb-macro-attributes/Cargo.toml, plugins/scarb-macro-attributes/README.md, plugins/scarb-macro-attributes/src/lib.rs, plugins/scarb-macro-interface/Cargo.toml, plugins/scarb-macro-interface/README.md, plugins/scarb-macro-interface/src/lib.rs, plugins/scarb-macro-interface/src/stable_abi.rs, scarb/Cargo.toml
commit-id:32dd0ae0
---
**Stack**:
- #1100
- #1110
- #1093
- #1091
- #1060
- #1139 ⬅
=> Create procedural macro interface library

extensions/scarb-cairo-run/src/main.rs, extensions/scarb-cairo-run/tests/arguments.rs, extensions/scarb-cairo-run/tests/examples.rs, website/docs/extensions/cairo-run.md
Closes #1089 
Please let me know if I've missed any tests cases, thanks!
=> Add `scarb cairo-run` tests

scarb/tests/build_cairo_plugin.rs
commit-id:e457ae12
---
**Stack**:
- #1161
- #1159
- #1157
- #1143
- #1151
- #1150
- #1148
- #1155
- #1100 ⬅
=> Add test case for procedural macro compilation

scarb/src/compiler/plugin/proc_macro/compilation.rs, scarb/src/compiler/plugin/proc_macro/mod.rs, scarb/src/ops/compile.rs, scarb/tests/build_cairo_plugin.rs
commit-id:1299f0be
---
**Stack**:
- #1161
- #1159
- #1157
- #1143
- #1151
- #1150
- #1155
- #1148 ⬅
=> Implement check command for cairo plugins

scarb/src/compiler/plugin/mod.rs, scarb/src/compiler/plugin/proc_macro/compilation.rs, scarb/src/compiler/plugin/proc_macro/mod.rs, scarb/src/ops/resolve.rs, scarb/tests/build_cairo_plugin.rs
commit-id:aeeb309e
---
**Stack**:
- #1161
- #1159
- #1157
- #1143
- #1155
- #1151
- #1150 ⬅
=> Run cargo fetch on workspace resolve

scarb/src/compiler/plugin/proc_macro/compilation.rs, scarb/tests/build_cairo_plugin.rs, utils/scarb-ui/src/message.rs
commit-id:fd15f5ab
---
**Stack**:
- #1161
- #1159
- #1157
- #1143
- #1155
- #1151 ⬅
=> Use json output format in cargo if set in scarb_ui

plugins/cairo-lang-macro/src/lib.rs, plugins/cairo-lang-macro/src/stable_abi.rs, scarb/src/compiler/plugin/proc_macro/host.rs
commit-id:89f844e2
---
**Stack**:
- #1165
- #1161
- #1159
- #1157
- #1143 ⬅
=> Add aux_data to proc macro result

Cargo.lock, Cargo.toml, scarb/src/compiler/helpers.rs
Fixes nightly
https://github.com/software-mansion/scarb/actions/runs/8164700273/job/22320502525
=> Adjust diagnostics reporter closure argument

scarb/src/compiler/db.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/src/ops/compile.rs
commit-id:af02bb94
---
**Stack**:
- #1166
- #1165 ⬅
=> Add collect aux data mechanism

plugins/cairo-lang-macro-attributes/src/lib.rs, plugins/cairo-lang-macro/src/lib.rs, scarb/tests/build_cairo_plugin.rs
commit-id:6c362eae
---
**Stack**:
- #1186
- #1185 ⬅
=> Remove macro_commons

Cargo.lock, plugins/cairo-lang-macro-stable/src/lib.rs, plugins/cairo-lang-macro/Cargo.toml, plugins/cairo-lang-macro/src/lib.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/tests/build_cairo_plugin.rs
commit-id:98fd5a13
---
**Stack**:
- #1200
- #1195
- #1194
- #1192 ⬅
=> Store file path and file id in token stream metadata

plugins/cairo-lang-macro/src/types/expansions.rs, scarb/src/compiler/db.rs, scarb/src/compiler/plugin/proc_macro/compilation.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host.rs
=> Allow defining multiple macros per package

Cargo.lock, Cargo.toml, extensions/scarb-cairo-run/Cargo.toml, extensions/scarb-cairo-test/Cargo.toml, extensions/scarb-cairo-test/src/main.rs, extensions/scarb-cairo-test/tests/build.rs
- **Update Cairo**
- **Allow testing without gas calculation**
=> Allow testing without gas calculation

plugins/cairo-lang-macro-attributes/src/lib.rs, plugins/cairo-lang-macro/src/types/mod.rs, scarb/tests/build_cairo_plugin.rs
commit-id:aee4271b
---
**Stack**:
- #1220
- #1219
- #1218
- #1217
- #1216 ⬅
=> Fix linkme call for multiple callback definitions

plugins/cairo-lang-macro/src/lib.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host.rs
commit-id:2136619c
---
**Stack**:
- #1220
- #1219
- #1218
- #1217 ⬅
=> Fix: expand with actual expansion name instead of package name

scarb/src/compiler/plugin/proc_macro/host.rs, scarb/tests/build_cairo_plugin.rs
commit-id:0504e339
---
**Stack**:
- #1220
- #1219 ⬅
=> Handle multiple aux data returns from code expansion

scarb/tests/build_cairo_plugin.rs
=> Add tests for macro name validations

plugins/cairo-lang-macro-attributes/src/lib.rs, plugins/cairo-lang-macro/src/types/mod.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host.rs
commit-id:b7466c6a
---
**Stack**:
- #1244
- #1235 ⬅
=> Implement inline macros expansion

plugins/cairo-lang-macro-attributes/src/lib.rs, plugins/cairo-lang-macro-stable/src/lib.rs, plugins/cairo-lang-macro/src/lib.rs, plugins/cairo-lang-macro/src/types/conversion.rs, plugins/cairo-lang-macro/src/types/mod.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/src/ops/compile.rs, scarb/tests/build_cairo_plugin.rs
commit-id:80676f2f
---
**Stack**:
- #1249
- #1244 ⬅
=> Resolve full path markers

.github/workflows/ci.yml, plugins/cairo-lang-macro/src/types/mod.rs
Nextest does not support doc tests https://github.com/nextest-rs/nextest/issues/16
- **Fix doc tests**
- **Run doc tests as part of CI**
=> Run doc tests in CI

scarb/tests/build_cairo_plugin.rs
**Stack**:
- #1264
- #1258
- #1262 ⬅
=> Refactor proc macro test project builder

plugins/cairo-lang-macro-attributes/src/lib.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/tests/build_cairo_plugin.rs
**Stack**:
- #1265
- #1264
- #1258 ⬅
=> Implement derive macros

plugins/cairo-lang-macro-attributes/src/lib.rs, plugins/cairo-lang-macro-stable/src/lib.rs, plugins/cairo-lang-macro/src/lib.rs, plugins/cairo-lang-macro/src/types/mod.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/tests/build_cairo_plugin.rs
commit-id:b3fd46d7
---
**Stack**:
- #1265
- #1264 ⬅
=> Parse attr arguments

plugins/cairo-lang-macro/src/types/mod.rs, scarb/tests/build_cairo_plugin.rs
=> Add From trait for Diagnostic -> Diagnostics

scarb/src/compiler/helpers.rs, scarb/tests/build.rs, utils/scarb-ui/src/components/typed.rs, utils/scarb-ui/src/lib.rs
=> Support diagnostic error codes

scarb/src/bin/scarb/main.rs, scarb/tests/subcommand.rs, utils/scarb-ui/src/args/verbosity.rs
commit-id:cae32b64
---
**Stack**:
- #1279
- #1278 ⬅
=> Fix SCARB_LOG setup for subcommands

scarb/src/sources/git/client.rs, scarb/tests/git_source.rs
commit-id:72d8d352
---
**Stack**:
- #1280
- #1279 ⬅
=> Do not override git checkout on each execution

Cargo.lock, utils/scarb-ui/CHANGELOG.md, utils/scarb-ui/Cargo.toml
=> Prepare scarb-ui release `0.1.5`

website/.vitepress/components/Footer.vue
=> Fix year in footer

website/.vitepress/components/Footer.vue
This reverts commit 439f1b3bd79269bc94b839e2683b798348279f52.
=> Revert "Fix year in footer (#1282)"

extensions/scarb-cairo-run/src/main.rs, extensions/scarb-cairo-run/tests/arguments.rs
=> Add option to choose function to run by name

Cargo.lock, Cargo.toml, extensions/scarb-snforge-test-collector/src/compilation/test_collector.rs
commit-id:42ae118c
---
**Stack**:
- #1296
- #1295
- #1294 ⬅
=> Update Cairo to include executables

scarb/src/compiler/compilers/lib.rs, scarb/tests/profiles.rs
commit-id:38745386
---
**Stack**:
- #1296
- #1295 ⬅
=> Add warning on no-executables & no-debug lib target build

Cargo.lock, Cargo.toml, extensions/scarb-cairo-language-server/Cargo.toml, extensions/scarb-cairo-language-server/tests/run.rs
=> Add LS E2E test

plugins/cairo-lang-macro-attributes/src/lib.rs, plugins/cairo-lang-macro/src/lib.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/tests/build_cairo_plugin.rs
commit-id:d3b61e99
---
**Stack**:
- #1298
- #1296 ⬅
=> Add executable attributes API

scarb/src/compiler/plugin/proc_macro/host.rs, scarb/tests/build_cairo_plugin.rs
=> Do not add new ast item, for last proc macro with no generated code

examples/starknet_hello_world/tests/contract_test.cairo, scarb/src/ops/resolve.rs, scarb/tests/build_targets.rs
commit-id:1d02f432
---
**Stack**:
- #1301
- #1300
- #1299 ⬅
=> Fix cfg set for integration test

Cargo.lock, Cargo.toml, extensions/scarb-doc/src/main.rs
- use cairo at [290f51f554c978180ca9d91177423305959cbed5](https://github.com/starkware-libs/cairo/commit/290f51f554c978180ca9d91177423305959cbed5)
- trait_item_names -> trait_required_item_names
=> [scarb-doc] Fix `trait_item_names`

scarb/src/ops/resolve.rs
commit-id:3f2ea15b
---
**Stack**:
- #1307
- #1306
- #1305
- #1300 ⬅
=> Refactor: extract cairo compilation unit for target to separate function

Cargo.lock, Cargo.toml, extensions/scarb-snforge-test-collector/tests/test.rs
Needed for `cairo-profiler`, easier to have this change on Scarb main for development purposes
=> Bump cairo

scarb/src/core/manifest/target.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/workspace.rs, scarb/src/ops/metadata.rs
commit-id:7964f21f
---
**Stack**:
- #1313
- #1312
- #1311 ⬅
=> Add `group_id` to target props

extensions/scarb-cairo-test/src/main.rs, extensions/scarb-cairo-test/tests/build.rs, scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/compilers/lib.rs, scarb/src/compiler/compilers/starknet_contract.rs, scarb/src/compiler/compilers/test.rs, scarb/src/compiler/db.rs, scarb/src/compiler/repository.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/ops/compile.rs, scarb/src/ops/metadata.rs, scarb/src/ops/resolve.rs, scarb/tests/build_targets.rs
commit-id:c5200c0d
---
**Stack**:
- #1313
- #1312 ⬅
=> Allow multiple targets on single Compilation unit component

extensions/scarb-cairo-test/tests/build.rs, scarb/src/ops/compile.rs, scarb/src/ops/resolve.rs
=> Resolve to grouped compilation units

scarb/tests/flock.rs
commit-id:84dfc333
---
**Stack**:
- #1329
- #1330
- #1331 ⬅
=> Increase timeout on flock test

scarb/tests/examples.rs
commit-id:ebced8a5
---
**Stack**:
- #1329
- #1330 ⬅
=> Ignore `dependencies` example project from build tests

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/expand.rs, scarb/src/bin/scarb/commands/mod.rs, scarb/src/ops/compile.rs, scarb/src/ops/expand.rs, scarb/src/ops/mod.rs
commit-id:8273b556
---
**Stack**:
- #1348
- #1347
- #1344 ⬅
=> Scarb expand initial impl

scarb/tests/build_cairo_plugin.rs, scarb/tests/expand.rs
=> Add test cases for expand

scarb/scarblib/test_plugin/Scarb.toml, scarb/src/core/package/name.rs, scarb/src/internal/restricted_names.rs, scarb/src/lib.rs, scarb/tests/metadata.rs, scarb/tests/profiles.rs
commit-id:d90b1698
---
**Stack**:
- #1362
- #1359
- #1358 ⬅
=> Rename test plugin to `cairo_test`

scarb/src/ops/expand.rs, scarb/tests/expand.rs
commit-id:8156f337
---
**Stack**:
- #1357
- #1356 ⬅
=> Allow expanding erroneous code

.github/dependabot.yml, Cargo.lock
- **Ignore starknet types from dependabot updates**
- **Update clap and url**
=> Ignore starknet types in dependabot rules, update deps

Cargo.lock, extensions/scarb-cairo-test/Cargo.toml, extensions/scarb-cairo-test/src/main.rs, scarb/src/compiler/compilers/test.rs, scarb/tests/build_targets.rs
commit-id:ad6c5bb5
---
**Stack**:
- #1364
- #1362 ⬅
=> Split TestCompilation into program and metadata

extensions/scarb-cairo-test/Cargo.toml, extensions/scarb-cairo-test/src/main.rs, extensions/scarb-cairo-test/tests/build.rs
=> Warn if cairo-test plugin is missing

Cargo.lock, Cargo.toml, scarb/tests/metadata.rs
- **Bump Cairo**
- **Fix todo**
=> Update Cairo 

extensions/scarb-cairo-run/src/main.rs
commit-id:e94e9d57
---
**Stack**:
- #1388
- #1387
- #1385 ⬅
=> Allow main function executable in cairo-run

scarb/scarblib/cairo_run/Scarb.toml, scarb/src/compiler/plugin/builtin.rs, scarb/src/compiler/plugin/mod.rs, scarb/src/core/package/name.rs, scarb/src/lib.rs, scarb/src/ops/resolve.rs
commit-id:37f9ce70
---
**Stack**:
- #1388
- #1387 ⬅
=> Create cairo-run executable plugin

website/package-lock.json, website/package.json
=> Update website dependencies

website/docs/guides/creating-a-new-package.md
commit-id:93a8841e
---
**Stack**:
- #1396
- #1395 ⬅
=> Add note about --snforge

website/docs/extensions/cairo-run.md
=> Doc cairo-run plugin

Cargo.lock, Cargo.toml, examples/dependencies/Scarb.toml, examples/hello_world/Scarb.toml, examples/starknet_hello_world/Scarb.toml, examples/starknet_multiple_contracts/Scarb.toml, examples/workspaces/Scarb.toml, extensions/scarb-doc/src/types.rs, extensions/scarb-doc/tests/test.rs, scarb/src/compiler/compilers/test.rs, scarb/tests/build.rs
- **Update cairo**
- **Disable deprecated cairo-doc code**
- **Add TestCompilationConfig to test compiler**
- **Change version to 2.6.4**
- **Add new edition**
=> Update Cairo, add TestCompilationConfig, disable deprecated cairo-doc impl

scarb/tests/build.rs
=> Statement map test: deserialize instead of is_object

Cargo.lock, scarb/Cargo.toml, scarb/src/compiler/helpers.rs, scarb/src/core/manifest/compiler_config.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/tests/profiles.rs
commit-id:65927daa
---
**Stack**:
- #1411
- #1410
- #1408 ⬅
=> Add inlining strategy to compiler config

.github/workflows/_check-release.yml, scarb/tests/snforge_init.rs
=> Add new/init --snforge e2e test

scarb/src/core/manifest/mod.rs, scarb/src/core/publishing/manifest_normalization.rs, scarb/tests/package.rs
- **Make packaging with publish=false possible**
- **Set manifest.publish default to true**
=> Allow packaging with publish=false

Cargo.lock, extensions/scarb-doc/Cargo.toml, extensions/scarb-doc/src/lib.rs, extensions/scarb-doc/src/main.rs, extensions/scarb-doc/src/metadata.rs, extensions/scarb-doc/src/metadata/compilation.rs, extensions/scarb-doc/src/types.rs, extensions/scarb-doc/src/versioned_json_output.rs, extensions/scarb-doc/tests/data/json_output_test_data.json, extensions/scarb-doc/tests/test.rs
commit-id:b9eb7559
---
**Stack**:
- #1464
- #1463
- #1462
- #1461
- #1460 ⬅
=> Extract package metadata info + refactor

extensions/scarb-doc/Cargo.toml, extensions/scarb-doc/src/docs_generation.rs, extensions/scarb-doc/src/docs_generation/markdown.rs, extensions/scarb-doc/src/docs_generation/markdown/book_toml.rs, extensions/scarb-doc/src/lib.rs
commit-id:b5f6227b
---
**Stack**:
- #1464
- #1463
- #1462
- #1461 ⬅
=> Add book.toml generation

extensions/scarb-doc/src/docs_generation.rs, extensions/scarb-doc/src/docs_generation/markdown.rs, extensions/scarb-doc/src/docs_generation/markdown/traits.rs
commit-id:9f0f272d
---
**Stack**:
- #1464
- #1463
- #1462 ⬅
=> Add traits for generating markdown docs

Cargo.lock, extensions/scarb-doc/Cargo.toml, extensions/scarb-doc/src/docs_generation.rs, extensions/scarb-doc/src/docs_generation/markdown.rs, extensions/scarb-doc/src/docs_generation/markdown/book_toml.rs, extensions/scarb-doc/src/docs_generation/markdown/summary.rs, extensions/scarb-doc/src/main.rs, extensions/scarb-doc/tests/data/hello_world/book.toml, extensions/scarb-doc/tests/data/hello_world/src/SUMMARY.md, extensions/scarb-doc/tests/data/hello_world/src/hello_world-Circle.md, extensions/scarb-doc/tests/data/hello_world/src/hello_world-CircleDrop.md, extensions/scarb-doc/tests/data/hello_world/src/hello_world-CirclePartialEq.md, extensions/scarb-doc/tests/data/hello_world/src/hello_world-CircleSerde.md, extensions/scarb-doc/tests/data/hello_world/src/hello_world-CircleShape.md, extensions/scarb-doc/tests/data/hello_world/src/hello_world-Color.md, extensions/scarb-doc/tests/data/hello_world/src/hello_world-FOO.md, extensions/scarb-doc/tests/data/hello_world/src/hello_world-Pair.md, extensions/scarb-doc/tests/data/hello_world/src/hello_world-Shape.md, extensions/scarb-doc/tests/data/hello_world/src/hello_world-fib.md, extensions/scarb-doc/tests/data/hello_world/src/hello_world-main.md, extensions/scarb-doc/tests/data/hello_world/src/hello_world.md, extensions/scarb-doc/tests/test.rs
=> Tests for md generation

utils/scarb-stable-hash/Cargo.toml, utils/scarb-stable-hash/README.md
commit-id:56c1efe9
---
**Stack**:
- #1497
- #1496
- #1495
- #1494
- #1493
- #1492
- #1491
- #1490 ⬅
=> Prepare scarb-stable-hash for publishing

plugins/cairo-lang-macro-stable/README.md
commit-id:d6079208
---
**Stack**:
- #1497
- #1496
- #1495
- #1494
- #1493
- #1492
- #1491 ⬅
=> Prepare cairo-lang-macro-stable for publishing

website/.vitepress/config.mjs, website/docs/reference/procedural-macro.md
commit-id:9204b5f2
---
**Stack**:
- #1497
- #1496
- #1495
- #1494
- #1493
- #1492 ⬅
=> Add procedural macros page to docs

scarb/tests/build_cairo_plugin.rs
commit-id:fe940136
---
**Stack**:
- #1497
- #1496
- #1495
- #1494
- #1493 ⬅
=> Drop rlib from build_cairo_plugin tests

Cargo.lock, plugins/cairo-lang-macro-attributes/Cargo.toml, plugins/cairo-lang-macro-attributes/README.md
commit-id:15faf15d
---
**Stack**:
- #1497
- #1496
- #1495
- #1494 ⬅
=> Prepare cairo-lang-macro-attributes for publishing

Cargo.lock, MAINTAINING.md, plugins/cairo-lang-macro/CHANGELOG.md, plugins/cairo-lang-macro/Cargo.toml, plugins/cairo-lang-macro/README.md, scarb/Cargo.toml
commit-id:874f8bab
---
**Stack**:
- #1497
- #1496
- #1495 ⬅
=> Prepare cairo-lang-macro for publishing

website/docs/reference/procedural-macro.md
commit-id:f1a5ffa4
---
**Stack**:
- #1497
- #1496 ⬅
=> Add link to docs.rs for cairo-lang-macro

extensions/scarb-doc/theme/CONTRIBUTING.md, extensions/scarb-doc/theme/README.md, extensions/scarb-doc/theme/cairo.js, extensions/scarb-doc/theme/highlight.js
[Issue #1457](https://github.com/orgs/software-mansion/projects/12/views/1?pane=issue&itemId=71242578)
=> Create highlight.js file for mdBook cairo support

website/docs/reference/manifest.md, website/docs/registries/publishing.md
=> Document Scarb.toml `publish` field

scarb/src/compiler/plugin/proc_macro/host.rs, scarb/tests/build_cairo_plugin.rs
=> Fix proc macro diagnostics stable pointer

scarb/src/core/registry/client/cache.rs, scarb/tests/http_registry.rs
=> Fix unnecessary downloads of cached registry packages

extensions/scarb-doc/src/docs_generation/markdown/traits.rs, extensions/scarb-doc/src/types.rs
- **Remove `allow(dead_code)` from scarb-doc**
- **Update todo comment**
=> Remove allow(dead_code) from scarb-doc

extensions/scarb-cairo-run/src/main.rs
In cases when program arguments size is too large it is handy to provide them via file.  
This PR introduces an optional CLI parameter `--arguments-file` for `scarb cairo-run` extension.
=> Feat: cairo-run extension: support --arguments-file optional parameter

extensions/scarb-doc/tests/features.rs, scarb/src/bin/scarb/commands/package.rs, scarb/src/bin/scarb/commands/publish.rs, scarb/src/bin/scarb/commands/test.rs, scarb/src/ops/compile.rs, scarb/src/ops/expand.rs, scarb/src/ops/resolve.rs, scarb/src/ops/subcommands.rs, scarb/tests/features.rs
=> Fix single package features in a workspace

Cargo.lock, Cargo.toml, extensions/scarb-doc/src/types.rs, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-Shape.md, extensions/scarb-doc/tests/data/hello_world_sub_package_no_features/src/hello_world_sub_package-test.md, extensions/scarb-doc/tests/data/hello_world_sub_package_with_features/src/hello_world_sub_package-test.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-Shape.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-test.md, extensions/scarb-doc/tests/data/json_output_test_data.json
Waiting for [this](https://github.com/starkware-libs/cairo/pull/6386) to be merged in cairo
=> Adjust tests to new trait types and consts signatures

website/docs/guides/dependencies.md, website/docs/troubleshooting.md
=> Update scarb docs

Cargo.lock, Cargo.toml, extensions/scarb-cairo-run/tests/examples.rs, extensions/scarb-cairo-test/tests/build.rs, scarb/src/compiler/compilers/starknet_contract/compiler.rs, scarb/src/compiler/compilers/test.rs
- **Update Cairo**
- **Pass contract declarations to compile_test_prepared_db**
fixes #1629
=> Pass contract declarations to compile_test_prepared_db / Cairo update

website/package-lock.json, website/package.json
https://github.com/software-mansion/scarb/security/dependabot/46
=> Update mermaid dependency

extensions/scarb-doc/src/lib.rs, extensions/scarb-doc/src/main.rs
=> Support UI verbosity in scarb-doc

Cargo.lock, Cargo.toml, extensions/scarb-cairo-run/tests/arguments.rs
Blocked by https://github.com/starkware-libs/cairo/pull/6525
=> Fix tests for cairo-run args validation

scarb/src/core/registry/client/cache.rs
`redb` will try to lock the db file, with exclusive lock. When exclusive lock cannot be acquired (e.g. when another Scarb process is using the db file simultaneously), Scarb will then remove the file completely and try to recreate it. 
This PR adds an advisory lock which synchronizes access to the db file between Scarb processes, so the lock can always be acquired.  
https://github.com/cberner/redb/blob/9ffa1d13dad343a8937a55540424dcfa45375a09/src/tree_store/page_store/file_backend/unix.rs#L37
=> Add advisory lock for registry cache db

plugins/cairo-lang-macro/Cargo.toml, plugins/cairo-lang-macro/src/types/mod.rs
**Stack**:
- #1686
- #1685
- #1684
- #1683
- #1718
- #1682
- #1681
- #1680
- #1679
- #1715
- #1676 ⬅
=> Add derives to `cairo-lang-macro`

Cargo.lock, Cargo.toml, plugins/cairo-lang-macro/Cargo.toml, plugins/cairo-lang-macro/src/types/mod.rs, utils/scarb-proc-macro-server-types/Cargo.toml, utils/scarb-proc-macro-server-types/README.md, utils/scarb-proc-macro-server-types/src/jsonrpc.rs, utils/scarb-proc-macro-server-types/src/lib.rs, utils/scarb-proc-macro-server-types/src/methods/defined_macros.rs, utils/scarb-proc-macro-server-types/src/methods/expand.rs, utils/scarb-proc-macro-server-types/src/methods/mod.rs
**Stack**:
- #1686
- #1685
- #1684
- #1683
- #1718
- #1682
- #1681
- #1680
- #1679
- #1715 ⬅
- #1676
=> Proc macro server API

Cargo.lock, Cargo.toml, plugins/cairo-lang-macro/Cargo.toml, plugins/cairo-lang-macro/src/types/mod.rs, scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/mod.rs, scarb/src/bin/scarb/commands/proc_macro_server.rs, utils/scarb-proc-macro-server-types/Cargo.toml, utils/scarb-proc-macro-server-types/README.md, utils/scarb-proc-macro-server-types/src/jsonrpc.rs, utils/scarb-proc-macro-server-types/src/lib.rs, utils/scarb-proc-macro-server-types/src/methods/defined_macros.rs, utils/scarb-proc-macro-server-types/src/methods/expand.rs, utils/scarb-proc-macro-server-types/src/methods/mod.rs
**Stack**:
- #1686
- #1685
- #1684
- #1683
- #1718
- #1682
- #1681
- #1680
- #1679 ⬅
- #1715
- #1676
=> Add `proc-macro-server` command

Cargo.lock, utils/scarb-test-support/Cargo.toml, utils/scarb-test-support/src/lib.rs, utils/scarb-test-support/src/proc_macro_server.rs
**Stack**:
- #1686
- #1685
- #1684
- #1683
- #1718 ⬅
=> Add test helpers

Cargo.lock, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/src/ops/proc_macro_server/methods/defined_macros.rs, scarb/src/ops/proc_macro_server/methods/mod.rs, scarb/src/ops/proc_macro_server/mod.rs, scarb/tests/proc_macro_server.rs, utils/scarb-test-support/Cargo.toml, utils/scarb-test-support/src/lib.rs, utils/scarb-test-support/src/proc_macro_server.rs
**Stack**:
- #1686
- #1685
- #1684
- #1683 ⬅
- #1718
=> Add `DefinedMacros` handler

plugins/cairo-lang-macro/src/lib.rs, plugins/cairo-lang-macro/src/types/conversion.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs
commit-id:55ec12c0
---
**Stack**:
- #1734
- #1722
- #1704
- #1700 ⬅
=> Avoid unnecessary allocations when freeing stable structs

Cargo.lock, plugins/cairo-lang-macro/CHANGELOG.md, plugins/cairo-lang-macro/Cargo.toml
commit-id:0bc65b53
---
**Stack**:
- #1741
- #1740 ⬅
=> Prepare `cairo-lang-macro` release `0.1.1`

Cargo.lock, scarb/Cargo.toml, utils/scarb-proc-macro-server-types/CHANGELOG.md, utils/scarb-proc-macro-server-types/Cargo.toml
=> Prepare `scarb-proc-macro-server-types` release `0.1.0`.

Cargo.lock, Cargo.toml, plugins/cairo-lang-macro-stable/src/lib.rs, plugins/cairo-lang-macro/Cargo.toml, plugins/cairo-lang-macro/src/lib.rs, plugins/cairo-lang-macro/src/types/conversion.rs, plugins/cairo-lang-macro/src/types/mod.rs, plugins/cairo-lang-macro/src/types/token.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/src/compiler/plugin/proc_macro/types.rs, scarb/tests/build_cairo_plugin.rs, scarb/tests/package.rs, scarb/tests/proc_macro_server.rs
commit-id:5e4b122f
Add token stream ser/de tests
---
**Stack**:
- #1749
- #1748
- #1745
- #1747
- #1722 ⬅
=> Allocate token's content into an arena

scarb/src/compiler/plugin/proc_macro/types.rs
commit-id:f0ce5a05
---
**Stack**:
- #1749
- #1748
- #1745
- #1761 ⬅
=> Skip whitespace prefix when creating the span

plugins/cairo-lang-macro/src/types/token.rs, scarb/tests/proc_macro_server.rs, utils/scarb-proc-macro-server-types/src/methods/mod.rs
commit-id:e6e81399
---
**Stack**:
- #1749
- #1748
- #1745 ⬅
=> Remove confusing default from token stream types

Cargo.lock, Cargo.toml, scarb/src/compiler/plugin/proc_macro/compilation.rs
- **Bump the non-critical group across 1 directory with 5 updates**
- **Fix build**
=> Update dependencies 

website/.vitepress/components/home/Terminal.vue, website/docs/extensions/starknet/contract-target.md, website/docs/reference/workspaces.md
Also fixes some broken links in related files
=> Prioritize registry deps in the docs

scarb/src/ops/compile.rs, scarb/tests/build_cairo_plugin.rs
fix https://github.com/software-mansion/scarb/issues/1779
=> Fix check command for cairo compilation units dependant on Scarb proc macros

plugins/cairo-lang-macro-stable/src/lib.rs, plugins/cairo-lang-macro/src/types/mod.rs, plugins/cairo-lang-macro/src/types/token.rs, scarb/src/compiler/plugin/proc_macro/types.rs, scarb/tests/build_cairo_plugin.rs, scarb/tests/proc_macro_server.rs, utils/scarb-test-support/src/proc_macro_server.rs
commit-id:107b5e17
---
**Stack**:
- #1749
- #1748 ⬅
=> Make TextSpan u32 to match the compiler one

Cargo.lock, Cargo.toml, plugins/cairo-lang-macro/Cargo.toml, plugins/cairo-lang-macro/src/lib.rs, plugins/cairo-lang-macro/src/types/token.rs, plugins/cairo-lang-quote/Cargo.toml, plugins/cairo-lang-quote/src/lib.rs, scarb/tests/proc_macro_quote.rs, utils/scarb-test-support/src/cairo_plugin_project_builder.rs
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: Mateusz Kowalski <mateusz.kowalski@swmansion.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Maksim Zdobnikau <43750648+DelevoXDG@users.noreply.github.com>
commit-id:face0a80
---
**Stack**:
- #1811
- #1810 ⬅
=> Quote macro (#1808)

scarb/src/core/resolver.rs, scarb/src/ops/resolve.rs, scarb/tests/build_targets.rs
- **Add test case for transitive dev deps**
- **Refactor: pull CU deps directly from graph**
=> Refactor: pull CU dependencies directly from dependency graph

scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/publishing/manifest_normalization.rs, scarb/tests/build_targets.rs
commit-id:12d49314
---
**Stack**:
- #1872
- #1871 ⬅
=> feat: allow declaring [executable] target

scarb/src/ops/resolve.rs, scarb/tests/gas_cfg.rs
=> Disable gas cfg when `enable-gas=false`

extensions/scarb-doc/src/types.rs, extensions/scarb-doc/tests/code/code_5.cairo, extensions/scarb-doc/tests/data/json_private_items_excluded.json, extensions/scarb-doc/tests/data/json_private_items_included.json
commit-id:0213c5ab
---
**Stack**:
- #1909
- #1908 ⬅
=> feat: exclude pub(crate) from docs

ARCHITECTURE.md, MAINTAINING.md, scarb/src/compiler/plugin/builtin.rs, scarb/src/compiler/plugin/mod.rs, website/.vitepress/components/home/Features.vue, website/.vitepress/config.mjs, website/docs.md, website/docs/cheatsheet.md, website/index.md
commit-id:386cef51
Replaces https://github.com/software-mansion/scarb/pull/1927
=> Rename StarkNet to Starknet

extensions/scarb-execute/src/main.rs, extensions/scarb-execute/tests/build.rs
commit-id:149c338e
Replaces https://github.com/software-mansion/scarb/pull/1928
=> Scarb execute: support panic reason print

extensions/scarb-execute/src/args.rs, extensions/scarb-execute/src/lib.rs, extensions/scarb-execute/tests/build.rs
=> Set execute default output format per target

scarb-metadata/src/lib.rs
**Stack**:
- #1921
- #1913
- #1970
- #1920
- #1919
- #1890 ⬅
=> Add plugin discovery utilities to scarb-metadata

scarb/src/compiler/plugin/proc_macro/host.rs
**Stack**:
- #1921
- #1913
- #1970
- #1920
- #1919 ⬅
=> Introduce procedural macro repository

scarb/src/compiler/plugin/collection.rs, scarb/src/compiler/plugin/mod.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/src/core/config.rs
**Stack**:
- #1921
- #1913
- #1970
- #1920 ⬅
=> Implement per-crate plugin collection

scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/db.rs, scarb/src/compiler/helpers.rs, scarb/src/ops/expand.rs, scarb/src/ops/lint.rs
**Stack**:
- #1921
- #1913
- #1970 ⬅
=> Add helpers to obtain `CrateId` of the `CompilationUnit`

scarb/src/bin/scarb/commands/proc_macro_server.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/src/ops/proc_macro_server/methods/defined_macros.rs, scarb/src/ops/proc_macro_server/methods/expand_attribute.rs, scarb/src/ops/proc_macro_server/methods/expand_derive.rs, scarb/src/ops/proc_macro_server/methods/expand_inline.rs, scarb/src/ops/proc_macro_server/methods/mod.rs, scarb/src/ops/proc_macro_server/mod.rs, scarb/tests/proc_macro_prebuilt.rs, scarb/tests/proc_macro_server.rs, utils/scarb-proc-macro-server-types/src/lib.rs, utils/scarb-proc-macro-server-types/src/methods/defined_macros.rs, utils/scarb-proc-macro-server-types/src/methods/expand.rs, utils/scarb-proc-macro-server-types/src/scope.rs, utils/scarb-test-support/src/proc_macro_server.rs
=> Respect per-crate plugins in Proc Macro Server

Cargo.lock, Cargo.toml, extensions/scarb-execute/src/lib.rs, extensions/scarb-execute/src/output.rs, extensions/scarb-execute/tests/build.rs, extensions/scarb-prove/Cargo.toml, extensions/scarb-prove/src/main.rs, extensions/scarb-verify/src/main.rs, scarb/tests/build.rs
- **Update deps**
- **Update reading panic info in scarb-execute**
=> fix nightly

scarb/src/compiler/compilers/starknet_contract/compiler.rs, scarb/tests/build_starknet_external_contracts.rs
fixes #2003
- **Add failing test case**
- **Deduplicate external contracts by full path**
=> Deduplicate external contracts by full path

plugins/cairo-lang-quote/src/lib.rs, scarb/tests/proc_macro_quote.rs
=> Fix `#token` interpolation in quote macro

scarb/src/core/manifest/summary.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/publishing/manifest_normalization.rs, scarb/src/ops/resolve.rs, scarb/tests/build_cairo_plugin.rs, scarb/tests/cairo_plugin_re_exports.rs, scarb/tests/local_registry.rs, scarb/tests/metadata.rs, scarb/tests/package.rs, website/docs/reference/manifest.md
fixes #2004
- **Fix duplicated component dependency on itself**
- **Cairo plugin reexports**
=> Cairo plugin reexports

extensions/scarb-cairo-test/src/main.rs, extensions/scarb-cairo-test/tests/build.rs
=> Fix cairo-test dep missing warning 

website/.vitepress/components/home/Download.vue, website/download.md
=> add starkup installation method

scarb/tests/build_targets.rs
commit-id:5b798390
---
**Stack**:
- #2028
- #2027 ⬅
=> Add test for test target contract compilation with error / warnings

.github/dependabot.yml, Cargo.lock
- **Update deps**
- **Ignore cairo-vm in dependabot**
=> Update deps 

website/.vitepress/config.mjs, website/constants.data.js, website/docs/extensions/cairo-run.md, website/docs/extensions/execute.md, website/docs/extensions/prove-and-verify.md, website/docs/guides/creating-executable-package.md, website/docs/reference/manifest.md, website/docs/reference/scripts.md, website/docs/reference/targets.md, website/docs/reference/workspaces.md, website/download.md
=> Add docs for execute, prove and verify, update docs

scarb/src/core/manifest/toml_manifest.rs, scarb/tests/metadata.rs
- **Remove redundant paths**
- **Add failing tests**
- **Fix collection of compiler config from profiles**
- **Add tests for compiler config precedence**
=> Fix compiler config collection with profiles

Cargo.lock, Cargo.toml, examples/dependencies/Scarb.toml, examples/hello_world/Scarb.toml, examples/starknet_hello_world/Scarb.toml, examples/starknet_multiple_contracts/Scarb.toml, examples/workspaces/Scarb.toml, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-CircleDrop.md, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-CirclePartialEq.md, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-CircleSerde.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-CircleDrop.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-CirclePartialEq.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-CircleSerde.md, extensions/scarb-execute/src/lib.rs, extensions/scarb-execute/tests/arguments.rs, extensions/scarb-execute/tests/build.rs, extensions/scarb-prove/src/main.rs, scarb/src/compiler/helpers.rs, scarb/src/core/manifest/compiler_config.rs, scarb/tests/build_cairo_plugin.rs, scarb/tests/metadata.rs
- **Prepare release `2.11.0`**
- **Allow specifying inlining-strategy via weight**
- **Update test expects**
- **Temp: use forked ls**
=> Prepare release `2.11`

.github/workflows/ci.yml, Cargo.toml, website/docs/extensions/prove-and-verify.md
- **Build website in ci**
- **Fix dead link**
- **Add empty patch section to cargo.toml**
=> Fix website build

website/.vitepress/components/home/Terminal.vue, website/docs/reference/workspaces.md
=> Update docs to suggest using registry dependencies instead of Git ones

.github/workflows/build-dev.yml
Just so we can test https://github.com/software-mansion/scarb/pull/2089 with workflow dispatch
=> Create empty build-dev job

extensions/scarb-doc/src/docs_generation.rs, extensions/scarb-doc/src/docs_generation/markdown/traits.rs, extensions/scarb-doc/src/lib.rs, extensions/scarb-doc/src/location_links.rs, extensions/scarb-doc/src/types.rs, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-CircleDrop.md, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-CirclePartialEq.md, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-CircleSerde.md, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-CircleShape.md, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-Shape.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-CircleDrop.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-CirclePartialEq.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-CircleSerde.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-CircleShape.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-Shape.md, extensions/scarb-doc/tests/data/hello_world_without_features/src/hello_world-CircleDrop.md, extensions/scarb-doc/tests/data/hello_world_without_features/src/hello_world-CirclePartialEq.md, extensions/scarb-doc/tests/data/hello_world_without_features/src/hello_world-CircleSerde.md, extensions/scarb-doc/tests/data/hello_world_without_features/src/hello_world-CircleShape.md, extensions/scarb-doc/tests/data/hello_world_without_features/src/hello_world-Shape.md, extensions/scarb-doc/tests/doc_hidden.rs
closes https://github.com/software-mansion/scarb/issues/1757
=> feat: doc links in signature

scarb/src/ops/compile.rs, scarb/src/ops/lint.rs, scarb/tests/build_cairo_plugin.rs
=> Do not compile unused proc macros when called with packages filter

.github/workflows/nightly.yml
fix tests in https://github.com/software-mansion/asdf-scarb/actions/runs/14402849441/job/40392302302
=> Do not mark nightly as latest when building a dev release

extensions/scarb-doc/src/docs_generation/markdown/traits.rs
closes https://github.com/software-mansion/scarb/issues/2177
=> fix: escape html

scarb/src/ops/metadata.rs, scarb/src/ops/resolve.rs, scarb/tests/proc_macro_v2_reexport.rs
- **Add a failing test case**
- **Deduplicate proc macro component collection**
=>  Deduplicate proc macro component collection

.github/workflows/_build-release.yml, .github/workflows/_check-release.yml, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, scarb/src/compiler/compilers/executable.rs, scarb/tests/patch.rs
- **Bump Cairo**
- **Update executable config**
=> Cairo update

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/lint.rs, scarb/src/ops/lint.rs, scarb/tests/lint.rs
resolves https://github.com/software-mansion/cairo-lint/issues/176
=> Introduce --target-names arg for scarb lint

scarb/src/compiler/plugin/proc_macro/v2/host/attribute/child_nodes.rs, scarb/src/compiler/plugin/proc_macro/v2/host/attribute/item_attribute.rs, scarb/src/compiler/plugin/proc_macro/v2/host/attribute/mod.rs, scarb/src/compiler/plugin/proc_macro/v2/host/mod.rs, scarb/src/compiler/plugin/proc_macro/v2/types.rs
commit-id:e3794f71
---
**Stack**:
- #2208
- #2207
- #2206 ⬅
=> Refactor: generalize parsing module item attributes

scarb/src/core/lockfile.rs, scarb/src/core/resolver.rs, scarb/src/resolver/algorithm/mod.rs, scarb/src/resolver/algorithm/provider.rs, scarb/src/resolver/mod.rs, scarb/src/resolver/primitive.rs
=> Automatically upgrade locked versions on conflicts

scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/publishing/manifest_normalization.rs, scarb/src/ops/resolve.rs, scarb/tests/features.rs
Enable features for deps
Add test cases
=> Enable features for deps

.github/workflows/ci.yml, utils/scarb-test-support/Cargo.toml
=> Run machete in CI

scarb/src/compiler/plugin/proc_macro/v2/host/attribute/inner_attribute.rs, scarb/tests/proc_macro_v2_expand.rs
=> Fix code mappings for inner attr expansion

website/docs/extensions/documentation-generation.md
closes https://github.com/software-mansion/scarb/issues/2255
=> feat: documentation update

extensions/scarb-doc/src/main.rs, extensions/scarb-doc/tests/core.rs
closes https://github.com/software-mansion/scarb/issues/2254
=> feat: add info to doc --build

Cargo.lock, plugins/cairo-lang-macro-attributes/Cargo.toml, plugins/cairo-lang-macro-stable/Cargo.toml, plugins/cairo-lang-macro/CHANGELOG.md, plugins/cairo-lang-macro/Cargo.toml, plugins/cairo-lang-quote/Cargo.toml, scarb/Cargo.toml, utils/scarb-proc-macro-server-types/CHANGELOG.md, utils/scarb-proc-macro-server-types/Cargo.toml, utils/scarb-test-support/src/cairo_plugin_project_builder.rs
- **Prepare `cairo-lang-macro-stable` release `2.0.0-rc.0`**
- **Prepare `cairo-lang-macro-attributes` release `0.2.0-rc.0`**
- **Prepare `cairo-lang-macro-quote` release `0.1.0-rc.0`**
- **Prepare `cairo-lang-macro` release `0.2.0-rc.0`**
- **Prepare `scarb-proc-macro-server-types` release `0.3.0-rc.0`**
=> Prepare crates release

extensions/scarb-doc/src/types/groups.rs, extensions/scarb-doc/src/types/module_type.rs, extensions/scarb-doc/tests/code/code_8.cairo, extensions/scarb-doc/tests/data/hello_world_doc_groups_reeksports/book.toml, extensions/scarb-doc/tests/data/hello_world_doc_groups_reeksports/src/SUMMARY.md, extensions/scarb-doc/tests/data/hello_world_doc_groups_reeksports/src/hello_world-inner_module-free_functions.md, extensions/scarb-doc/tests/data/hello_world_doc_groups_reeksports/src/hello_world-inner_module-inner_function_visible_in_group.md, extensions/scarb-doc/tests/data/hello_world_doc_groups_reeksports/src/hello_world-inner_module-visible_in_reeksports.md, extensions/scarb-doc/tests/data/hello_world_doc_groups_reeksports/src/hello_world-inner_module.md, extensions/scarb-doc/tests/data/hello_world_doc_groups_reeksports/src/hello_world-modules.md, extensions/scarb-doc/tests/data/hello_world_doc_groups_reeksports/src/hello_world-top_level_fn_visible_in_group.md, extensions/scarb-doc/tests/data/hello_world_doc_groups_reeksports/src/hello_world.md, extensions/scarb-doc/tests/data/hello_world_doc_groups_reeksports/src/visible-free_functions.md, extensions/scarb-doc/tests/data/hello_world_doc_groups_reeksports/src/visible.md, extensions/scarb-doc/tests/data/json_doc_groups_reeksports.json, extensions/scarb-doc/tests/dog_groups_in_reeksports.rs
**Stack**:
- #2288
- #2275
- #2274
- #2273
- #2272
=> doc groups for module reeksports

.github/workflows/ci.yml
Issue and used workaround: https://github.com/taiki-e/install-action/issues/1005
=> Pin nextest version in CI

install.sh
- #2327
- #2328
---
Closes #2228
=> Add completions setup to the install script 

scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/fingerprint.rs, scarb/src/compiler/mod.rs, scarb/src/lib.rs
Co-authored-by: Maksim Zdobnikau <maksim.zdobnikau@swmansion.com>
=> Define fingerprint structure

scarb/src/compiler/plugin/proc_macro/v1/host.rs, scarb/src/compiler/plugin/proc_macro/v2/host/mod.rs
It seems insignificant, but from my quick benchmarks can give as much as 10% gain in OZ tests compilation
=> Exit early for ast items not using any proc macros in generate code

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/bin/scarb/fsx.rs, scarb/src/bin/scarb/main.rs, scarb/src/compiler/compilers/lib.rs, scarb/src/compiler/compilers/starknet_contract/artifacts_writer.rs, scarb/src/compiler/compilers/starknet_contract/compiler.rs, scarb/src/compiler/plugin/proc_macro/v1/ffi.rs, scarb/src/compiler/plugin/proc_macro/v1/host.rs, scarb/src/compiler/plugin/proc_macro/v2/ffi.rs, scarb/src/compiler/plugin/proc_macro/v2/host/inline.rs, scarb/src/compiler/plugin/proc_macro/v2/host/mod.rs, scarb/src/ops/compile.rs
- **Add tracing-chrome profile config**
- **Add more instruments to compilation**
- **Add instruments to proc macro generate code**
- **fixup! Add more instruments to compilation**
=> Profiling config

scarb/src/ops/lint.rs, scarb/tests/lint.rs
Resolves https://github.com/software-mansion/cairo-lint/issues/375
=> [Linter] Fail on --deny-warnings after all packages were linted

scarb/src/core/lockfile.rs, scarb/src/core/registry/client/local.rs, scarb/src/core/registry/index/record.rs, scarb/src/core/registry/source_map.rs, scarb/src/core/source/id.rs, scarb/src/ops/resolve.rs, scarb/src/sources/registry.rs, scarb/tests/yanked.rs, utils/scarb-test-support/src/registry/local.rs, website/docs/reference/lockfile.md, website/docs/registries/custom-registry.md
closes https://github.com/software-mansion/scarb/issues/2178
connected to https://github.com/software-mansion/scarbs.xyz/pull/532
=> implement feature use yanked packages only if cached

extensions/scarb-cairo-language-server/tests/run.rs, scarb/tests/features.rs
Order of messages may not be deterministic
=> Fix flaky test cases

.github/workflows/ci.yml, website/github.data.mjs
=> Authenticate github API requests in website CI

scarb/src/core/manifest/toml_manifest.rs, scarb/tests/workspace.rs
As doced in https://docs.swmansion.com/scarb/docs/reference/manifest.html#cairo
=> Warn on compiler config specified in ws member manifest

scarb/src/flock.rs
fixes https://github.com/software-mansion/scarb/issues/1877
Problem: 
two processes - trying to acquire packages from different sources (registry and git) requiring  _registry cache db lock_ and  _package cache_ lock respectively - acquire each one lock. Then one of the processes tries to acquire package from the other source, requiring a lock that is being held by the other process, so it waits synchronously for the lock blocking the executor. Analogical actions of the second proces result in deadlock.   
Solution: 
await locks in separate threads to avoid blocking. 
Reproduce:
I have two simple projects with the same Scarb.toml content:
[package]
name = "brutus"
version = "0.1.0"
edition = "2024_07"
[dependencies]
openzeppelin_merkle_tree = "0.17.0"
alexandria_math = { git = …
=> fix: multiple parallel builds deadlock

scarb/src/ops/resolve.rs, scarb/src/resolver/provider.rs
- **Start resolving in a named thread**
- **Add tracing instrument for resolver**
=> Add tracing instrument for resolver thread

Cargo.lock, plugins/cairo-lang-macro-attributes/Cargo.toml, plugins/cairo-lang-macro-stable/Cargo.toml, plugins/cairo-lang-macro/CHANGELOG.md, plugins/cairo-lang-macro/Cargo.toml, plugins/cairo-lang-quote/Cargo.toml, scarb/Cargo.toml, utils/scarb-proc-macro-server-types/CHANGELOG.md, utils/scarb-proc-macro-server-types/Cargo.toml
- **Prepare `cairo-lang-macro-attributes` release `0.2.0`**
- **Prepare `cairo-lang-macro-stable` release `2.0.0`**
- **Prepare `cairo-lang-quote` release `0.1.0`**
- **Prepare `cairo-lang-macro` release `0.2.0`**
- **Prepare `scarb-proc-macro-server-types` release `0.3.0`**
=> Prepare release of proc macro crates

.github/workflows/publish_plugins.yml
Test run: https://github.com/software-mansion/scarb/actions/runs/16752513808
=> Publish builtin plugins to dev registry

scarb/src/compiler/incremental/compilation.rs, scarb/src/compiler/incremental/fingerprint.rs, scarb/src/compiler/incremental/source.rs
- **Parallelize calculating local checksums on fingerprint creation**
- **Add tracing span**
- **Parallelize calculating plugin checksums**
- **Warmup fingerprint digests**
=> Parallelize calculating checksums for fingerprints

scarb/src/core/manifest/target.rs, scarb/tests/build_targets.rs
closes https://github.com/software-mansion/scarb/issues/704
=> validate file steams custom source path target

scarb/src/compiler/mod.rs, scarb/src/compiler/plugin/proc_macro/v2/types.rs, scarb/src/compiler/syntax.rs
=> Optimize building token stream

Cargo.lock, Cargo.toml
No more changes after this apart from releasing
=> Last LS bump for 2.12.1

scarb/src/core/manifest/target.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/publishing/manifest_normalization.rs, scarb/tests/build_targets.rs, website/docs/reference/manifest.md, website/docs/reference/targets.md
closes https://github.com/software-mansion/scarb/issues/2526
=> support default params for test targets

plugins/cairo-lang-macro-attributes/src/lib.rs, plugins/cairo-lang-macro/src/lib.rs, scarb/src/compiler/incremental/fingerprint.rs, scarb/src/compiler/plugin/collection.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/mod.rs, scarb/src/compiler/plugin/proc_macro/v2/ffi.rs, scarb/tests/incremental.rs
Change proc macro post process callback into an enum
Define fingerprint callback interface for procedural macro instances
Add macro for defining fingeprint callbacks
=> Define macro fingerprint callback interface

scarb/src/core/manifest/summary.rs, scarb/src/core/registry/patch_map.rs, scarb/src/core/registry/patcher.rs, scarb/src/core/registry/source_map.rs, scarb/src/core/source/id.rs, scarb/src/ops/resolve.rs, scarb/src/resolver/mod.rs, scarb/src/resolver/provider.rs, scarb/src/sources/registry.rs, scarb/tests/audits.rs, scarb/tests/http_registry.rs, website/docs/reference/specifying-dependencies.md
The flag added in @2560 is automatically ignored for dev deps
- #2560
- #2561
- #2617
- #2563
- #2562 
- #2566
- #2575
- #2576
=> Bypass audit requirement for dev deps

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/list.rs, scarb/src/bin/scarb/commands/mod.rs, scarb/src/core/mod.rs, scarb/src/core/registry/index/record.rs, scarb/src/lib.rs, scarb/src/sources/git/client.rs, scarb/tests/list.rs, website/docs/guides/dependencies.md
Display package versions with yank and audit status
Closes #2428 
- #2560
- #2561
- #2617
- #2563
- #2562 
- #2566
- #2575
- #2576
=> Add `scarb list` to list registry package versions 

website/docs/reference/workspaces.md
follow up for https://github.com/software-mansion/scarb/pull/2603
=> update docs: workspace target-defaults

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/list.rs, scarb/tests/list.rs
- #2560
- #2561
- #2617
- #2563
- #2562 
- #2566
- #2575
- #2576
=> Limit amount of versions listed by `scarb list`; Add `--all` flag

website/docs/extensions/oracles/shell.md
Something I missed during review of #2661  😅
=> fix docs <> oracles

extensions/scarb-cairo-test/src/main.rs, extensions/scarb-execute/src/lib.rs, extensions/scarb-execute/tests/oracles/wasm/mod.rs, utils/scarb-oracle-hint-service/src/assets.rs, utils/scarb-oracle-hint-service/src/connection.rs, utils/scarb-oracle-hint-service/src/connections/mod.rs, utils/scarb-oracle-hint-service/src/connections/shell.rs, utils/scarb-oracle-hint-service/src/connections/stdio_jsonrpc/mod.rs, utils/scarb-oracle-hint-service/src/connections/wasm/mod.rs, utils/scarb-oracle-hint-service/src/hint_service.rs, utils/scarb-oracle-hint-service/src/lib.rs, utils/scarb-oracle-hint-service/src/protocol.rs
=> Implement assets mechanism on the oracle hint service side

website/.vitepress/config.mjs, website/docs/extensions/oracles/overview.md, website/docs/extensions/oracles/wasm.md
=> Document wasm protocol

extensions/scarb-cairo-test/Cargo.toml, extensions/scarb-execute/Cargo.toml
This reverts commit ab728f3ce8d55b3b80ecae3cb0e46c67f05658f3.
fix #2669
=> Revert "Disable WASM oracle protocol until it's fully implemented (#2668)"
