Cargo.lock, Cargo.toml, scarb/Cargo.toml, utils/create-output-dir/Cargo.toml, utils/create-output-dir/README.md, utils/create-output-dir/src/lib.rs
=> Make `create-output-dir` crate not depend on `cargo-util`. Release `create-output-dir` 1.0.0

scarb/src/core/config.rs, scarb/src/core/source/id.rs, scarb/src/ops/subcommands.rs, scarb/src/ui/mod.rs, scarb/tests/e2e/build.rs, scarb/tests/e2e/subcommand.rs
=> Pass scarb env vars

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/main.rs, scarb/src/core/config.rs, scarb/src/ops/subcommands.rs, scarb/tests/e2e/build.rs, scarb/tests/e2e/subcommand.rs, scarb/tests/e2e/support/command.rs
=> Allow overriding target directory

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/mod.rs, scarb/src/bin/scarb/commands/remove.rs, scarb/src/manifest_editor/mod.rs, scarb/src/manifest_editor/remove.rs, scarb/tests/e2e/main.rs, scarb/tests/e2e/remove.rs
fix #93 
Adds `remove` command with `rm` as alias. Currently, all it does is just removing the specified dependencies from the dependency table of a manifest file. It doesn't do any workspace clean up like `cargo rm` as there's no support for proper workspace yet as well as other types of dependency (e.g., dev, build).
I tried to refer as much as possible to `cargo`, so if there's anything lacking please let me know.
=> Add `scarb rm`

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/init.rs, scarb/src/bin/scarb/commands/new.rs, scarb/src/ops/new.rs, scarb/tests/e2e/new_and_init.rs
Fix #80 
Refactor `write_vcs_ignore` a bit to allow some flexibility **in case** we want to support other version control systems in the future.
=> Initialize Git repository on `scarb new` & `scarb init`

scarb/src/manifest_editor/add.rs, scarb/tests/e2e/add.rs
Fix #128 
Will sort if the `[dependencies]` section is already sorted otherwise leave it as is.
=> Sort `[dependencies]` section on `scarb add`

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/add.rs, scarb/src/bin/scarb/commands/remove.rs
Fix #127 
Referring to Cargo, the problem I'm seeing with this if later we want to add flags like `--exclude` / `--all` for commands like `scarb build`, we can just add new fields in `PackagesFilter`, but then we can't disable the individual flags for commands that don't require them and they'd also be shown in the help message. Or maybe that's not something we should worry about atm? Wdyt?
=> Generalize logic for getting selected package

scarb/src/manifest_editor/add.rs, scarb/src/sources/git/mod.rs, scarb/tests/e2e/add.rs
Fix #108
Add trailing slash in tests because they have empty paths.
=> Canonicalize Git URL in `scarb add`

scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/compilers/lib.rs, scarb/src/compiler/compilers/starknet_contract.rs, scarb/src/compiler/helpers.rs, scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/mod.rs, scarb/src/core/registry/mod.rs, scarb/src/metadata/mod.rs, scarb/src/ops/resolve.rs, scarb/tests/e2e/build.rs, website/pages/docs/reference/manifest.mdx
And use it to pass `sierra-replace-ids` to the compiler.
Fix #160
=> Add `[cairo]` section to Scarb.toml

scarb/src/bin/scarb/args.rs, website/components/home/jumbo.tsx, website/pages/docs/cheatsheet.mdx, website/pages/docs/guides/dependencies.mdx, website/pages/docs/guides/working-on-an-existing-package.mdx, website/pages/docs/reference/specifying-dependencies.mdx
Change references to `quirenox` in our website to `quaireaux_math` since they have recently changed their project structure.
=> Change references to `quirenox` in our website to `quaireaux_math`

Cargo.lock, Cargo.toml, scarb-cairo-language-server/Cargo.toml, scarb-cairo-language-server/README.md, scarb-cairo-language-server/src/main.rs
=> Add cairo-language-server binary

scarb/src/bin/scarb/commands/commands.rs, scarb/tests/e2e/subcommand.rs
Fix listing subcommands to include Scarb exe directory, as in #277
=> List subcommands from Scarb exe dir

website/pages/docs/reference/manifest.mdx
- Remove package name regex from docs
- Explicitly state that it must not be a Cairo keyword
=> Clarify information about package names in docs

website/pages/docs/guides/working-on-an-existing-package.mdx
Suggesting to update the terminal command for users to arrive right into the location where the `math` package is
=> Update: CLI command in working-on-an-existing-package.mdx

scarb/tests/e2e/scripts.rs
This avoids the problem of ASDF not being able to find `.tool-versions` in temporary directories.
fix #230
=> Use Bash instead of Python in scripts tests

.github/workflows/release.yml, website/components/releaseContext.tsx, website/data/github.ts, website/package-lock.json, website/package.json, website/pages/docs/install.mdx
=> Publish MUSL builds

scarb/src/resolver/mod.rs
commit-id:97b4cbb8
---
**Stack**:
- #345
- #344
- #343
- #346
- #342
- #341
- #340
- #339
- #338 ⬅
=> Port `sub_dependencies` test from `hex_solver`

extensions/scarb-cairo-language-server/Cargo.toml, scarb/src/ops/clean.rs
commit-id:73e1fc5c
---
**Stack**:
- #372
- #371 ⬅
- #370
=> Make `scarb clean` not error if target directory is not present

Cargo.lock, Cargo.toml, scarb-metadata/Cargo.toml, scarb-metadata/src/command.rs, scarb-metadata/src/lib.rs, scarb-metadata/src/packages_filter.rs, scarb/Cargo.toml, scarb/src/bin/scarb/args.rs, scarb/src/core/workspace.rs, scarb/src/ops/metadata.rs, scarb/tests/e2e/scripts.rs
1. `extra` and `cairo_plugins` fields
2. `PackagesFilter`
3. Non-panicking getters for packages and compilation units
4. `builder` feature is not default now
=> New scarb-metadata features

scarb/src/compiler/compilers/starknet_contract.rs, scarb/src/core/manifest/target.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/internal/mod.rs, scarb/src/internal/serdex.rs, scarb/tests/e2e/build_starknet_contract_allowed_libfuncs.rs
=> Introduce `internal::serdex` module and `RelativeUtf8PathBuf` to solve TOML paths issues

install.sh, website/pages/docs/install.mdx
- Stop `check_proc` and `get_bitness` warnings from popping up
- Use `sh` consistently in docs instead 
- Allow skipping `PATH` modification (e.g. for docker builds)
=> Update install script

scarb/src/compiler/compilers/starknet_contract.rs, scarb/tests/e2e/build_starknet_contract.rs, website/pages/docs/starknet/contract-target.mdx
- Consistent with starknet artifacts naming convention
- Avoids name collisions (target names are guaranteed to be unique across all units)
=> Use `target_name` instead of `package_name` for `starknet_artifacts` map file

scarb/src/bin/scarb/commands/commands.rs
Before: 
```
build               : Compile current project
cairo-language-server: /Users/maciektr/Projects/scarb/target/debug/scarb-cairo-language-server
cairo-run           : /Users/maciektr/Projects/scarb/target/debug/scarb-cairo-run
```
After:
```
build                 : Compile current project
cairo-language-server : /Users/maciektr/Projects/scarb/target/debug/scarb-cairo-language-server
cairo-run             : /Users/maciektr/Projects/scarb/target/debug/scarb-cairo-run
```
=> Fix commands listing table cells width

extensions/scarb-cairo-test/src/main.rs
Sometimes a broken Scarb installation may result in `scarb cairo-test` calling another revision of `scarb-cairo-test` binary, which may cause confusing errors.
=> Cairo-test: Warn when scarb version does not match

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/fetch.rs, scarb/src/bin/scarb/commands/mod.rs, scarb/tests/fetch.rs
as `scarb metadata` uses `ops::resolve` 
- closes: https://github.com/software-mansion/scarb/issues/487
=> Adds `scarb fetch`

.github/workflows/nightly.yml
Resolves #544 
Accessing artifact with name that contains version tag (eg. `scarb-v0.6.0+nightly-2023-08-09-aarch64-apple-darwin.tar.gz`) is not feasible in a scenario when we want to install nightly version because there is no easy way of knowing which stable release it is based on.
That's why we modify the name of the artifacts in nightly release workflow to omit "vX.Y.Z+" right before uploading it to the release.
=> Rename nightly artifacts to be accessible from bash scripts

website/docs/reference/global-directories.md
This wasn't a big issue, because both Windows and macOS have by default case-insensitive file systems. For sanity’s sake, though, we should be consistent with source: https://github.com/software-mansion/scarb/blob/06c4dc21cc0b80274ee8d8374ee5a3b0ed10e17c/scarb/src/core/dirs.rs#L26
=> Fix global directories casing in documentation

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/cache_path.rs, scarb/src/bin/scarb/commands/mod.rs, scarb/tests/cache.rs
=> added cache-path command

Cargo.lock, Cargo.toml, extensions/scarb-cairo-test/src/main.rs, scarb/src/version.rs
Depends on https://github.com/starkware-libs/cairo/pull/3926
=> Print Sierra version in `scarb --version`

Cargo.lock, extensions/scarb-cairo-run/Cargo.toml, extensions/scarb-cairo-run/src/main.rs, extensions/scarb-cairo-test/Cargo.toml, extensions/scarb-cairo-test/src/main.rs, scarb/src/bin/scarb/args.rs, scarb/src/core/package/mod.rs, scarb/src/core/workspace.rs, scarb/src/ops/metadata.rs, utils/scarb-ui/Cargo.toml, utils/scarb-ui/src/args/mod.rs, utils/scarb-ui/src/args/packages_filter.rs, utils/scarb-ui/src/lib.rs
- The subsequent commit will deprecate original struct in `scarb-metadata`
- The new version uses `anyhow` instead of `thiserror`
- Some error messages were updated to follow `help:` convention
---
**Stack**:
- #587
- #585
- #584
- #583 ⬅
=> Copy `PackagesFilter` into `scarb-ui`

scarb-metadata/Cargo.toml, scarb-metadata/src/lib.rs, scarb-metadata/src/packages_filter.rs
fix #385
---
**Stack**:
- #587
- #585
- #584 ⬅
=> Deprecate `packages_filter` feature in `scarb-metadata`

.github/workflows/ci.yml
This shaves a handful of minutes from CI execution time. The drawback is that we will fight for concurrency more.
=> Increase test parallelism in CI workflow

scarb/src/ops/subcommands.rs, scarb/tests/test_subcommand.rs, utils/scarb-ui/src/components/status.rs
- Status should always be a single verb.
- Print what command is going to be called, like Cargo does
---
**Stack**:
- #587
- #585 ⬅
=> Properly use `Status` message when testing workspace

Cargo.lock, extensions/scarb-cairo-run/Cargo.toml, extensions/scarb-cairo-run/src/main.rs, extensions/scarb-cairo-run/tests/examples.rs, utils/scarb-ui/src/message.rs
Extra: reordered methods in `Message` trait to group them by medium, so that linters will not yell, as this new order makes more sense.
JSON support to be included in later commits.
=> Basic implementation of `scarb-ui` in `scarb cairo-run`

scarb/src/core/manifest/dependency.rs, scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/summary.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/manifest/version_req.rs, scarb/src/core/registry/mod.rs, scarb/src/ops/metadata.rs, scarb/src/ops/resolve.rs, scarb/tests/resolver.rs
=> Consider prerelease versions if `version` field of a dependency is unspecified

utils/scarb-test-support/src/filesystem.rs
Fixes #468
Test was failing because of asdf's Scarb installation interfering with it. 
Solution to that problem is to run Scarb process without `ASDF_DATA_DIR` paths in `PATH` env var.
=> Fix `errors_when_missing_script_and_cairo` test

README.md
As Foundry [is working on their init template](https://github.com/foundry-rs/starknet-foundry/pull/565), which will cover our mostly requested use-case, we do not see the need to invest into generic init templates idea anymore.
=> Cross init templates off the roadmap

examples/hello_world/Scarb.toml, scarb/src/ops/new.rs
External template scripts want to use `scarb add` to auto-add necessary dependencies, and this comment makes the outcome ugly. We also don't really need it, so let's just remove it for simplicity.
=> Remove example dependency comment from the template

Cargo.lock, Cargo.toml, scarb/src/ops/fmt.rs, scarb/tests/build.rs, scarb/tests/fmt.rs, website/docs/guides/formatting.md
Resolves #609
Introduces `[tool.fmt]` section to `Scarb.toml` with `sort-imports` boolean flag
=> Support import sorting via manifest configuration

.github/workflows/nightly.yml
Pinning Cairo version to branch doesn't work when Cargo.toml already specifies that branch, because lockfile locks the branch on some commit in the past. We need to explicitly set the dependency as a commit hash, to override what is in the lockfile.
=> Set cairo version to latest main commit explicitly in nightly workflow

Cargo.lock, Cargo.toml, scarb-metadata/src/lib.rs, scarb/Cargo.toml, scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/tests/metadata.rs, website/docs/reference/manifest.md
=> Infer readme

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/ops/subcommands.rs, scarb/src/process.rs, scarb/tests/subcommand.rs, utils/scarb-test-support/Cargo.toml, utils/scarb-test-support/src/main.rs, utils/scarb-test-support/tests/hack.rs
=> Fix exec_replace

scarb/src/bin/scarb/commands/build.rs, scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/compilers/lib.rs, scarb/src/compiler/compilers/starknet_contract.rs, scarb/src/compiler/compilers/test.rs, scarb/src/compiler/mod.rs, scarb/src/compiler/repository.rs, scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/summary.rs, scarb/src/core/manifest/target.rs, scarb/src/core/manifest/target_kind.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/package/mod.rs, scarb/src/core/registry/mod.rs, scarb/src/core/resolver.rs, scarb/src/ops/compile.rs, scarb/src/ops/resolve.rs, scarb/src/resolver/mod.rs, scarb/tests/build_targets.rs
1. There were no reasons to disallow `[[target.lib]]`.
2. On the other hand, it would be cool to expect target names to have package-name-style validation.
---
**Stack**:
- #697
- #710
- #675
- #657
- #646
- #712 ⬅
=> Fix `TomlTargetKind` parsing rules

scarb/src/bin/scarb/commands/external.rs, scarb/src/core/manifest/scripts.rs, scarb/src/ops/subcommands.rs
- `scarb test` cannot replace scarb process
- subcommands should be able to do so
=> Execute cairo-test as script instead of exec_replace when testing pkg

website/.vitepress/config.mjs, website/docs/registries/package-tarball.md
**Stack**:
- #697
- #710
- #675
- #657
- #646 ⬅
=> Document package tarballs

scarb/tests/build.rs, scarb/tests/build_starknet_contract.rs, scarb/tests/build_starknet_external_contracts.rs, scarb/tests/fmt.rs, scarb/tests/git_source.rs, scarb/tests/git_source_network.rs, scarb/tests/metadata.rs, scarb/tests/resolver_with_git.rs, utils/scarb-test-support/src/project_builder.rs, utils/scarb-test-support/src/workspace_builder.rs
This PR adds a new DSL for specifying dependencies in `ProjectBuilder` and `WorkspaceBuilder`. It is capable of expressing all cases for which we have been falling back to strings currently, and also it can now do things like amending auto-generated deps for e.g. paths.
This PR updates all string- and TOML table-based usages of old API. It does not migrate explicit paths usage to auto-generation for `ChildPaths` whereverr we want to ensure paths are properly treated as relative.
---
**Stack**:
- #697
- #710
- #726 ⬅
=> DepBuilder DSL

extensions/scarb-cairo-test/src/main.rs, extensions/scarb-cairo-test/tests/examples.rs
commit-id:83b56a17
---
**Stack**:
- #727
- #723 ⬅
=> Use packages filter env var in cairo-test

Cargo.lock, utils/scarb-ui/Cargo.toml, utils/scarb-ui/src/args/packages_filter.rs
It was barely used.
---
**Stack**:
- #753
- #752
- #751
- #750
- #749 ⬅
=> Remove `indoc` dependency from `scarb-ui`

scarb/src/internal/restricted_names.rs, scarb/src/ops/package.rs, scarb/tests/package.rs
**Stack**:
- #758
- #757
- #748
- #746
- #733
- #697 ⬅
=> Check archive filenames

scarb/src/core/publishing/source.rs, scarb/src/lib.rs, scarb/tests/package.rs
This PR makes `scarb package` check for `.scarbignore` files when determining package source files set. This is a trivial addition thanks to features of the `ignore` crate.
Supporting this file is effectively a similar feature to the include/exclude fields of Cargo (https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields). This PR fixes #644 then, as we do not want to create multiple ways of achieving the same thing.
---
**Stack**:
- #758
- #757
- #748
- #746 ⬅
=> Support `.scarbignore` files when packaging

scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/publishing/manifest_normalization.rs
**Stack**:
- #758
- #757
- #748 ⬅
=> Move large struct `DetailedTomlDependency` into a `Box` and use `Cow` to avoid cloning it

scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/publishing/manifest_normalization.rs
**Stack**:
- #767
- #758
- #757 ⬅
=> Add `registry` field to dependency schema

scarb/src/sources/git/client.rs
commit-id:9f949bd5
---
**Stack**:
- #778
- #777
- #775
- #774 ⬅
=> Revert matching parsing errors in git db client contains method

scarb/src/core/registry/index/base_url.rs, scarb/src/core/registry/index/config.rs, scarb/src/core/registry/index/mod.rs, scarb/src/core/registry/index/record.rs, scarb/src/core/registry/index/template_url.rs, scarb/src/core/registry/mod.rs, scarb/src/core/source/id.rs
**Stack**:
- #794
- #793
- #790
- #792
- #783
- #767 ⬅
=> Implement base data models for registry index

scarb/src/flock.rs, scarb/src/ops/package.rs
**Stack**:
- #798
- #793
- #790
- #792 ⬅
=> Fix `ops::package` leaving old path in created `FileLockGuard`

MAINTAINING.md
I have added a branch protection rule, that would stop me from creating `v` named branch in future - let me know if it causes any problems.
=> Fix release branch naming in maintaining docs

Cargo.lock, Cargo.toml, extensions/scarb-cairo-test/tests/examples.rs, utils/test-for-each-example/Cargo.toml, utils/test-for-each-example/src/lib.rs
We fail to run cairo-test on alexandria with cairo main. This results in failed tests on https://github.com/software-mansion/scarb/pull/821
This PR adds an ignore argument on  test_for_each_example, so we can skip running cairo-test on dependencies example.
=> Allow ignoring example project by name in test_for_each_example macro

scarb/src/bin/scarb/args.rs, scarb/tests/profiles.rs
=> Make profile args take precedence over env

scarb/src/core/registry/client/local.rs, scarb/src/core/registry/client/mod.rs, scarb/src/core/registry/index/mod.rs, scarb/src/core/registry/mod.rs, scarb/src/core/registry/package_source_store.rs, scarb/src/core/registry/source_map.rs, scarb/src/core/source/id.rs, scarb/src/flock.rs, scarb/src/internal/fsx.rs, scarb/src/sources/mod.rs, scarb/src/sources/registry.rs, utils/scarb-test-support/src/project_builder.rs
This implementation focuses solely on local registries, and it has almost no security.
---
**Stack**:
- #819
- #818
- #809
- #808
- #807
- #806
- #805
- #803
- #802
- #799
- #798
- #793
- #790 ⬅
=> Initial implementation of `RegistrySource`

scarb/tests/local_registry.rs, utils/scarb-test-support/src/lib.rs, utils/scarb-test-support/src/registry/local.rs, utils/scarb-test-support/src/registry/mod.rs
These tests depend on both #790 and #793, hence they come in separate PR.
---
**Stack**:
- #819
- #818
- #809
- #808
- #807
- #806
- #805
- #803
- #802
- #799
- #798 ⬅
=> Add basic tests for local registry

scarb/src/compiler/plugin/builtin.rs
=> Include `get_dep_component!` and `get_dep_component_mut!` macros in the `starknet` package

Cargo.lock, Cargo.toml, scarb/src/core/registry/client/http.rs, scarb/src/core/registry/client/mod.rs, scarb/src/core/registry/index/config.rs, scarb/src/sources/registry.rs, scarb/tests/http_registry.rs, utils/scarb-test-support/src/registry/http.rs, utils/scarb-test-support/src/registry/mod.rs
**Stack**:
- #819
- #818
- #809
- #808
- #807
- #806
- #805
- #803 ⬅
=> Initial implementation of HTTP registry client

scarb/src/core/config.rs, scarb/src/resolver/mod.rs, utils/scarb-ui/src/lib.rs
**Stack**:
- #846
- #845
- #844
- #843
- #819
- #818
- #809
- #808
- #807 ⬅
=> Impl `Clone` for `Ui`

extensions/scarb-cairo-test/src/main.rs
Here's an overview of changes as a diff...
```diff
fn find_testable_targets(...) {
-   Take metadata and of the package id.
+   Take package metadata
-   Loop through packages in metadata
-   Filter packages with ID matching package id.
-   Flat map and clone targets of the matching package(s?)
+   Get targets of the package
Filter the test kind
-   Return vec of TargetMetadata
+   Return vec of &TargetMetadata
}
```
=> chore: minor optimisation

scarb/tests/profiles.rs
Fixes #849
Removing a test when it's failing isn't a good idea but `cannot_choose_both_release_and_dev` test that created from `cannot_choose_both_release_and_by_name` (in #825)  is a duplicate of `cannot_choose_both_dev_and_release` test.
It could be fixed by adjusting stderr message assertion to 
```sh
Usage: scarb[..] --dev --global-cache-dir <DIRECTORY> --global-config-dir <DIRECTORY> <COMMAND>
```
but that would be the exact same thing as `cannot_choose_both_dev_and_release`.
=> Remove redundant `cannot_choose_both_dev_and_release` test

scarb/src/ops/package.rs, scarb/src/sources/git/client.rs
**Stack**:
- #875
- #874
- #873 ⬅
=> Fix: unify path_in_vcs format accross target os

scarb/src/ops/package.rs, scarb/tests/package.rs
=> Throw an error in `scarb package` with non-`[lib]` packages

scarb/src/core/config.rs, scarb/src/core/registry/client/cache.rs, scarb/src/core/registry/client/http.rs, scarb/src/core/registry/client/local.rs, scarb/src/core/registry/client/mod.rs, scarb/src/sources/registry.rs, scarb/tests/http_registry.rs, scarb/tests/local_registry.rs
This PR lays groundwork for implementing caching of `RegistryClient` instances.
It just sets up all the types and refactors, no caching is done yet.
There is also a small functional change: local registry client does not print
`Unpacking` status in normal mode. This wasn't a big deal, and it allowed removing
the `is_offline` method from `RegistryClient`.
---
**Stack**:
- #892
- #846
- #845
- #844
- #819
- #818
- #809
- #808 ⬅
=> Introduce `RegistryClientCache` stub

scarb/src/ops/package.rs, scarb/tests/local_registry.rs
Although the `set_metadata_in_mode` call should set `mtime` to a deterministic value, it fails to do so due to
https://github.com/alexcrichton/tar-rs/issues/341. Also, the constant value used there is funky and I do not feel convinced about its stability. Therefore, we use our own `mtime` value explicitly here.
fix #883
=> Use constant `mtime` for packaged tarballs

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/core/registry/client/cache.rs, scarb/src/core/registry/client/http.rs, scarb/src/core/registry/client/local.rs, scarb/src/core/registry/client/mod.rs, scarb/src/internal/fsx.rs, scarb/src/sources/registry.rs, utils/scarb-ui/src/lib.rs
NOTE: Nothing is cached actually yet, because no registry client uses hooks provided by this code. This will come in subsequent PRs.
---
**Stack**:
- #892
- #846
- #845
- #844
- #819
- #818
- #809 ⬅
=> Implement caching of records returned from registry clients

scarb/src/core/registry/client/http.rs, scarb/src/core/registry/client/mod.rs, scarb/tests/http_registry.rs, utils/scarb-test-support/src/simple_http_server.rs
---
**Stack**:
- #909
- #906
- #892
- #846
- #845
- #844
- #819 ⬅
=> Implement records caching on HttpRegistryClient level

scarb/src/flock.rs
This data structure will be later used in Tokio-based code which writes to the file protected by this guard.
---
**Stack**:
- #909
- #906
- #892
- #846
- #845
- #844 ⬅
=> Add `AsyncFileLockGuard`

scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/helpers.rs, scarb/src/core/dirs.rs, scarb/src/core/registry/client/http.rs, scarb/src/core/registry/package_source_store.rs, scarb/src/core/workspace.rs, scarb/src/flock.rs, scarb/src/internal/lazy_directory_creator.rs, scarb/src/sources/git/client.rs, scarb/src/sources/git/mod.rs
This surprisingly small addition required some bigger changes. Filesystems are now lifetime-unbound, and rely on internal `Arc`s instead of references. Technically this means higher heap pressure and slower code due to increased use of atomics, but `Filesystem`s are by nature not part of hot paths, so this is fine.
---
**Stack**:
- #909
- #906
- #892
- #846
- #845 ⬅
=> Impl `Clone` for `Filesystem`

scarb/src/core/registry/client/http.rs, scarb/tests/http_registry.rs
This PR implements permanent caching of index configs. These resources are expected to change very rarely, so event the ETag-style approach is expected to be too talkative to the server. I expect registry administrators to publicly announce to their users that they have to clear the cache manually (by calling `scarb cache clean`) if they change their configs.
fix #741
---
**Stack**:
- #909
- #906
- #892 ⬅
=> Cache index configs

Cargo.lock, Cargo.toml, extensions/scarb-snforge-test-collector/Cargo.toml, extensions/scarb-snforge-test-collector/src/compilation.rs, extensions/scarb-snforge-test-collector/src/compilation/test_collector.rs, extensions/scarb-snforge-test-collector/src/compilation/test_collector/config.rs, extensions/scarb-snforge-test-collector/src/compilation/test_collector/plugin.rs, extensions/scarb-snforge-test-collector/src/compilation/test_collector/sierra_casm_generator.rs, extensions/scarb-snforge-test-collector/src/crate_collection.rs, extensions/scarb-snforge-test-collector/src/main.rs, extensions/scarb-snforge-test-collector/src/metadata.rs
Tests will be added to ensure bumping cairo versions doesn't break anything. Before introducing it in snforge will be tested on snforge side locally at first, then with the nightly build.
Example usage:
```console
scarb --manifest-path simple_package/Scarb.toml test-collector --output-path simple_package/target/snforge/simple_package_tests.sierra.json
```
=> Add snforge test collector

website/docs/extensions/testing.md
Wrong link [here](https://github.com/software-mansion/scarb/blob/main/website/docs/extensions/testing.md?plain=1#L13)
=> Fix link in `Testing Scarb projects` docs section

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/fmt.rs, scarb/src/ops/fmt.rs, scarb/tests/fmt.rs
- add an emit option to stdout to match some linter specs
- modify FmtAction to have an exclusive option to: fix, check or emit formatted file.
- not modify the existing flag --check for clarity, though --check and --emit flags are mutually exclusive (--check overrides --emit)
Requesting help for: getting familiar with the repository: 
- what should the clap argument for emit be? is this fine?
```rust
#[derive(Parser, Clone, Debug)]
pub struct FmtArgs {
// ...
#[arg(short, long)]
pub emit: Option<EmitTarget>,
// ...
}
```
- How should the `emit_formatted_file` function behave? Should it output a specific per-path message like the diff printing function, i.e.: `ws.config().ui().print(format!("{file}"))` versus `ws.config().ui().print(format!("Diff in file {}:\n {}", path.display(), diff))` …
=> feat: add emit option

scarb/tests/fmt.rs
Fix tests on windows. 
Failing: https://github.com/software-mansion/scarb/actions/runs/6977109530/job/18986494006
Passing: https://github.com/software-mansion/scarb/actions/runs/6983522605/job/19004771911
=> Fix emit tests: replace stdout_matches with stdout_eq

scarb/src/core/resolver.rs, scarb/src/resolver/mod.rs, scarb/tests/lockfile_checksums.rs, utils/scarb-test-support/src/fsx.rs
=> Implement lockfiles checksums verification

scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/publishing/manifest_normalization.rs, scarb/tests/build.rs, scarb/tests/local_registry.rs, scarb/tests/metadata.rs, utils/scarb-test-support/src/project_builder.rs
=> Add `dev-dependencies`

scarb/src/ops/package.rs, scarb/tests/package.rs
Resolves #869.
Unlike cargo which completely ignores VCS when using `--allow-dirty`, we still want to package the info because that seems reasonably. 
There is an edge case when `--allow-dirty` flag which reads a hash of HEAD commit fails due to repository not having any commits. In that case we want to treat it like there was no VCS information to include at all and just ignore it.
=> Handle case when packaged repo does not have any commits

.github/workflows/ci.yml
This PR re-enabled Windows CI after a series of Windows-specific failures caught up by our daily check workflow. We want to make all contributors be more aware of Windows specifics, and reduce burden of us having to frequently make hotfixes.
=> Enable Windows CI

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/add.rs, scarb/src/bin/scarb/commands/remove.rs, scarb/src/manifest_editor/add.rs, scarb/src/manifest_editor/dep_type.rs, scarb/src/manifest_editor/mod.rs, scarb/src/manifest_editor/remove.rs, scarb/tests/add.rs, scarb/tests/remove.rs, website/docs/cheatsheet.md, website/docs/guides/dependencies.md, website/docs/reference/manifest.md, website/docs/reference/specifying-dependencies.md
add info in docs
fix docs
commit-id:2ccf4af8
dev-dependencies -> development dependencies
---
**Stack**:
- #976
- #977 ⬅
=> add `--dev` flag to `add` and `rm`

scarb-metadata/src/lib.rs, scarb/src/core/manifest/target_kind.rs, scarb/src/ops/metadata.rs, scarb/tests/metadata.rs
Just like in Cargo (https://doc.rust-lang.org/cargo/commands/cargo-metadata.html), expose dependency kind in Scarb metadata
=> Add dep_kind to dependency metadata

website/constants.data.js, website/docs/guides/creating-a-new-package.md, website/docs/reference/manifest.md, website/download.md
- Make ASDF installation guide more noticeable
- Add edition constant in website def
- Add a starknet section to creating package guide
=> Docs: Add starknet section to guide, edition constant and asdf installation note

extensions/scarb-snforge-test-collector/src/metadata.rs, extensions/scarb-snforge-test-collector/tests/test.rs
Closes https://github.com/foundry-rs/starknet-foundry/issues/1460
The solution is to fetch dependencies from unit test compilation unit.
After talking with @mkaput we decided that to ensure this heuristic solution doesn't break we check if all other test compilation units have the same dependencies (excluding dependencies being sources for integration tests i. e., starting with `{package_path}/tests/`).
=> Use dev-deps during compilation in `snforge-test-collector`

Cargo.lock
This solves the issue that prevented Cargo from upgrading
the `hashbrown` crate.
=> Regenerate Cargo.lock, upgrading all dependencies alongside

extensions/scarb-snforge-test-collector/src/compilation/test_collector/config.rs, extensions/scarb-snforge-test-collector/tests/test.rs
This PR is connected to the [issue](https://github.com/foundry-rs/starknet-foundry/issues/618) from the Starknet-Foundry repo. It adds support for the `available_gas` attribute in the `test-collector`
=> `availabe_gas` support in snfoundry-test-collector

scarb/src/core/manifest/dependency.rs, scarb/src/core/manifest/summary.rs, scarb/src/resolver/mod.rs, scarb/tests/metadata.rs
=> Do not propagate dev deps

.github/CODEOWNERS
@mkaput is going to maintain CairoLS and will not attempt to review each PR going into Scarb from now on.
=> Remove @mkaput from CODEOWNERS

extensions/scarb-snforge-test-collector/src/compilation/test_collector/config.rs, extensions/scarb-snforge-test-collector/tests/test.rs
This needs to be `None` because older versions of snforge would crash on `u32::max` (which seems to be a default value), with an error that the attribute is not supported.
=> Fix `snforge-test-collector`'s default `available_gas` value

extensions/scarb-snforge-test-collector/src/metadata.rs, scarb-metadata/src/lib.rs, scarb/src/compiler/db.rs, scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/publishing/manifest_normalization.rs, scarb/src/ops/metadata.rs, scarb/tests/metadata.rs, website/docs/reference/manifest.md
This reverts commit c55a25d6b8ada5d40b6facd9444a60a8498c0016.
=> Revert "Rename `experimental_features` -> `allow_features` (#1058)"

scarb/src/ops/subcommands.rs, scarb/tests/test_subcommand.rs
Although is sounded tempting to allow users to override Scarb extensions bundled in the default installation, that caused more harm than good in practice. For example, if the user is working on a custom build of Scarb, but has another one installed globally (for example via ASDF), then their custom build would use global extensions instead of the ones it was built with, which would be very confusing.
=> Reverse search order in `find_external_subcommand`

scarb/src/compiler/compilers/starknet_contract.rs, scarb/tests/build_starknet_contract.rs
=> Add `module_path` to `ContractArtifacts`

Cargo.lock, Cargo.toml, extensions/scarb-snforge-test-collector/src/compilation/test_collector.rs
Needed because of the changing output function types
=> `snforge-test-collector`: nightly fix & `cairo-lang-*` bump

.github/workflows/_build-release.yml, .github/workflows/_check-release.yml
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
=> CI: Use M1 runners wherever possible

scarb-metadata/src/lib.rs, scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/compilers/test.rs, scarb/src/compiler/helpers.rs, scarb/src/ops/metadata.rs, scarb/src/ops/resolve.rs
Depends on #1084 
Resolves #1076
=> Expose per-compilation-unit cfg sets in scarb metadata

.github/dependabot.yml
Motivation: should match the compiler used
=> Exclude cairo-felt from dependabot patterns

Cargo.lock, Cargo.toml, extensions/scarb-snforge-test-collector/Cargo.toml, extensions/scarb-snforge-test-collector/src/compilation/test_collector.rs, extensions/scarb-snforge-test-collector/src/compilation/test_collector/function_finder.rs, extensions/scarb-snforge-test-collector/tests/test.rs
https://github.com/foundry-rs/starknet-foundry/issues/1394
=> [`snforge-test-collector`] Add `TestDetails` to `TestCaseRaw`

Cargo.lock, plugins/cairo-lang-macro/Cargo.toml, scarb/Cargo.toml, scarb/src/compiler/db.rs, scarb/src/compiler/plugin/mod.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/src/compiler/plugin/proc_macro/mod.rs
commit-id:18967d01
---
**Stack**:
- #1143
- #1148
- #1100
- #1110
- #1093
- #1091
- #1060 ⬅
=> Add `ProcMacroHost` definition

scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host.rs
Resolves #1127
commit-id:e59370d2
---
**Stack**:
- #1159
- #1157
- #1143
- #1151
- #1150
- #1148
- #1100
- #1155
- #1110
- #1093
- #1091 ⬅
=> Implement procedural macro host `generate_code` for attribute macro

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/compiler/db.rs, scarb/src/compiler/plugin/proc_macro/compilation.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/src/compiler/plugin/proc_macro/mod.rs, scarb/src/core/dirs.rs
Resolves #1128
commit-id:a3155bbf
---
**Stack**:
- #1159
- #1157
- #1143
- #1151
- #1150
- #1148
- #1100
- #1155
- #1110
- #1093 ⬅
=> Implement loading shared libraries for proc macro plugins

scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/plugin/proc_macro/compilation.rs, scarb/src/compiler/plugin/proc_macro/mod.rs, scarb/src/ops/compile.rs, scarb/src/ops/resolve.rs, scarb/src/process.rs, scarb/tests/build_cairo_plugin.rs
Resolves #1129
commit-id:aebc6424
---
**Stack**:
- #1161
- #1159
- #1157
- #1143
- #1151
- #1150
- #1148
- #1100
- #1155
- #1110 ⬅
=> Procedural macro compilation

scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/compilers/lib.rs, scarb/src/compiler/compilers/starknet_contract.rs, scarb/src/compiler/compilers/test.rs, scarb/src/compiler/db.rs, scarb/src/compiler/helpers.rs, scarb/src/compiler/mod.rs, scarb/src/compiler/plugin/proc_macro/compilation.rs, scarb/src/compiler/repository.rs, scarb/src/ops/compile.rs, scarb/src/ops/metadata.rs, scarb/src/ops/resolve.rs
commit-id:bf749c51
---
**Stack**:
- #1165
- #1161
- #1159
- #1157
- #1143
- #1155 ⬅
=> Change compilation unit to enum

plugins/cairo-lang-macro-attributes/src/lib.rs, plugins/cairo-lang-macro-stable/src/lib.rs, plugins/cairo-lang-macro/src/lib.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/tests/build_cairo_plugin.rs
commit-id:e557eb16
---
**Stack**:
- #1166
- #1165
- #1161
- #1159
- #1174 ⬅
=> Fix memory managment around the FFI-barrier

Cargo.lock, plugins/cairo-lang-macro-attributes/Cargo.toml, plugins/cairo-lang-macro-attributes/src/lib.rs, plugins/cairo-lang-macro-stable/src/ffi.rs, plugins/cairo-lang-macro-stable/src/lib.rs, plugins/cairo-lang-macro/src/lib.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/tests/build_cairo_plugin.rs
commit-id:f06e9653
---
**Stack**:
- #1166
- #1165
- #1161
- #1159 ⬅
=> Implement procedural macro diagnostics

scarb/tests/build_cairo_plugin.rs
commit-id:ecc87fd5
---
**Stack**:
- #1166
- #1165
- #1161 ⬅
=> Add remove/replace proc macro e2e tests

Cargo.lock, Cargo.toml, extensions/scarb-cairo-language-server/Cargo.toml, extensions/scarb-cairo-test/Cargo.toml, extensions/scarb-snforge-test-collector/Cargo.toml, scarb/Cargo.toml, scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/compilers/starknet_contract.rs, scarb/src/core/source/id.rs, scarb/src/internal/mod.rs, scarb/src/sources/git/canonical_url.rs, utils/scarb-stable-hash/Cargo.toml, utils/scarb-stable-hash/src/lib.rs
**Stack**:
- #1194
- #1192
- #1186
- #1188
- #1187 ⬅
=> Move Scarb StableHash to separate crate

Cargo.lock, plugins/cairo-lang-macro-stable/src/lib.rs, plugins/cairo-lang-macro/Cargo.toml, plugins/cairo-lang-macro/src/lib.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/tests/build_cairo_plugin.rs
commit-id:eacd6dd6
---
**Stack**:
- #1195
- #1194
- #1192
- #1186
- #1188 ⬅
=> Store AuxData as Vec<u8> instead of serde/string

Cargo.lock, Cargo.toml, plugins/cairo-lang-macro-attributes/Cargo.toml, plugins/cairo-lang-macro-attributes/src/lib.rs, plugins/cairo-lang-macro/Cargo.toml, plugins/cairo-lang-macro/src/lib.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/tests/build_cairo_plugin.rs
commit-id:a9ba1335
---
**Stack**:
- #1200
- #1195
- #1194
- #1192
- #1186 ⬅
=> Implement aux_data callback

scarb/src/compiler/compilation_unit.rs
Currently, all the variant of the enum derive `Clone` and `Debug`. Could be helpful to clone regardless of the variant if it's ok for you. :+1:
=> fix: derive Clone and Debug for CompilationUnit enum

plugins/cairo-lang-macro-attributes/src/lib.rs, plugins/cairo-lang-macro-stable/src/lib.rs, plugins/cairo-lang-macro/src/lib.rs, plugins/cairo-lang-macro/src/types/conversion.rs, plugins/cairo-lang-macro/src/types/expansions.rs, plugins/cairo-lang-macro/src/types/mod.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/tests/build_cairo_plugin.rs
commit-id:3dc2a19c
---
**Stack**:
- #1200
- #1195 ⬅
=> Register macro expansion capabilities

scarb/src/core/registry/client/local.rs, scarb/src/flock.rs, scarb/src/ops/lockfile.rs, utils/scarb-build-metadata/build.rs
commit-id:77034927
---
**Stack**:
- #1220
- #1219
- #1218
- #1217
- #1216
- #1215
- #1214
- #1221
- #1222
- #1213 ⬅
=> Rust update - fix build and clippy erorrs

xtask/src/nightly_release_notes.rs
commit-id:006f3571
---
**Stack**:
- #1220
- #1219
- #1218
- #1217
- #1216
- #1215
- #1214
- #1221
- #1222 ⬅
=> Fix nightlies pipeline after rust package id spec update

plugins/cairo-lang-macro-attributes/src/lib.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/tests/build_cairo_plugin.rs
commit-id:fbea0ed1
---
**Stack**:
- #1220
- #1219
- #1218
- #1217
- #1216
- #1215
- #1214 ⬅
=> Rename aux data collection to post processing

plugins/cairo-lang-macro-attributes/src/lib.rs, plugins/cairo-lang-macro/src/lib.rs, plugins/cairo-lang-macro/src/types/conversion.rs, plugins/cairo-lang-macro/src/types/expansions.rs, plugins/cairo-lang-macro/src/types/mod.rs, scarb/tests/build_cairo_plugin.rs
commit-id:1ca84df1
---
**Stack**:
- #1220
- #1219
- #1218
- #1217
- #1216
- #1215 ⬅
=> Rewrite cairo-lang-macro docs

scarb/tests/build_cairo_plugin.rs
commit-id:6f8ff1da
---
**Stack**:
- #1220
- #1219
- #1218 ⬅
=> Add test case with multiple macros

extensions/scarb-snforge-test-collector/src/compilation/test_collector.rs, extensions/scarb-snforge-test-collector/tests/test.rs
Closes https://github.com/foundry-rs/starknet-foundry/issues/1934
=> Consider a case when the test fn return types are actually an empty vec

extensions/scarb-cairo-run/tests/arguments.rs, extensions/scarb-cairo-run/tests/examples.rs, scarb/tests/build.rs
commit-id:38e43ae7
---
**Stack**:
- #1244
- #1235
- #1243 ⬅
=> Fix asserts with time units

plugins/cairo-lang-macro-attributes/src/lib.rs, plugins/cairo-lang-macro-stable/src/lib.rs, plugins/cairo-lang-macro/src/types/conversion.rs, plugins/cairo-lang-macro/src/types/mod.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/tests/build_cairo_plugin.rs
commit-id:3f7d4d4c
---
**Stack**:
- #1264
- #1258
- #1262
- #1261 ⬅
=> Replace result enum with single struct

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/init.rs, scarb/src/bin/scarb/commands/new.rs, scarb/src/ops/new.rs
Closes  #1208
- Added `--snforge` flag that enables forge template for
- `new` command
- `init` command
On forge side https://github.com/foundry-rs/starknet-foundry/pull/2113
=> Add forge template to `scarb new` and `scarb init` under separate flag

extensions/scarb-snforge-test-collector/src/compilation/test_collector/config.rs, extensions/scarb-snforge-test-collector/src/felt252.rs, extensions/scarb-snforge-test-collector/src/main.rs, extensions/scarb-snforge-test-collector/tests/test.rs
Closes #1317
Fixes felt serialization in `snforge-test-collector` by using wrapper with custom `serde::Serialize` implementation that is mimicking old `Felt252` implementation (wrapper over `BigUint`)
=> Fix felt serialization in `snforge-test-collector`

scarb/src/sources/git/client.rs
Gm guys,
wondering if this is a typo or an actual fix.
In dojo we're using scarb as a dependency, and when we compile a package of the workspace this error occurs, which prevent us from building a specific package depending on scarb explicitly.
However, when the whole workspace is compiled, it works fine.
Inspecting the scarb code base, everywhere it seems to be `tracing::trace`, `tracing::debug` etc... Is this `tracing::log::debug` forgotten, but not a direct problem as it compiles fine anyway?
Thanks for the feedback!
=> fix: propose consistent usage of debug from tracing

plugins/cairo-lang-macro/src/types/mod.rs
Add derives for `Diagnostic`, `Severity` and `Diagnostics`, also `Deref` for `Diagnostics`. In current shape these are very hard to work with, which is caused by lack of basic functionalities (like `Eq`), also `Diagnostics` can't be merged or extended with ready `Diagnostic` (only by matching on it's `Severity` and then choosing correct method to reconstruct in again)
=> Add derives for `Severity` and `Diagnostics`

Cargo.lock, extensions/scarb-doc/Cargo.toml, extensions/scarb-doc/src/compilation.rs, extensions/scarb-doc/src/main.rs, extensions/scarb-doc/src/types.rs, extensions/scarb-doc/tests/test.rs
Next PR will add nested attributes to the structures:
- struct members
- enum variants
- impl items
- trait items
=> [scarb-doc] Add initial crate structures

utils/scarb-ui/src/components/spinner.rs, utils/scarb-ui/src/lib.rs, utils/scarb-ui/src/widget.rs
=> Print Cargo logs with SpinnerBar::println

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/expand.rs, scarb/src/ops/compile.rs, scarb/src/ops/expand.rs, scarb/src/ops/resolve.rs
commit-id:2ec662b7
---
**Stack**:
- #1348
- #1347 ⬅
=> Add target selector

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/expand.rs, scarb/src/bin/scarb/commands/fmt.rs, scarb/src/ops/expand.rs, scarb/src/ops/fmt.rs, scarb/tests/expand.rs
=> Add option to emit expand result to stdout

examples/dependencies/Scarb.toml, examples/hello_world/Scarb.toml, examples/starknet_hello_world/Scarb.toml, examples/starknet_multiple_contracts/Scarb.toml, examples/workspaces/Scarb.toml, examples/workspaces/crates/addition/Scarb.toml, examples/workspaces/crates/fibonacci/Scarb.toml, extensions/scarb-cairo-test/tests/build.rs, scarb/src/core/manifest/summary.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/registry/mod.rs, scarb/src/ops/resolve.rs, scarb/src/resolver/mod.rs, scarb/src/sources/registry.rs, scarb/tests/build_targets.rs, scarb/tests/expand.rs, scarb/tests/git_source.rs, scarb/tests/metadata.rs, scarb/tests/profiles.rs, utils/scarb-test-support/src/project_builder.rs
commit-id:83a53c59
---
**Stack**:
- #1362
- #1359 ⬅
=> Require explicit dependence on `cairo_test` (i.e. `test_plugin`)"

scarb/src/core/manifest/compiler_config.rs, scarb/src/core/manifest/toml_manifest.rs, website/docs/reference/manifest.md
Forgot to do it when the semantic changed
=> Update statements mappings docs

scarb/src/ops/new.rs
It seems that's what is expected there https://github.com/foundry-rs/starknet-foundry/blob/74da40441b7bf51582fc053dcc4d4d751bef1f44/crates/forge/src/init.rs#L104
Also, I've submitted a PR in snforge repo that sets correct manifest paths in scarb new https://github.com/foundry-rs/starknet-foundry/pull/2223
=> Pass pkg parent to snforge init

scarb/src/core/manifest/mod.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/package/mod.rs, scarb/src/core/publishing/manifest_normalization.rs, scarb/src/ops/publish.rs, scarb/tests/local_registry.rs, scarb/tests/package.rs
=> Add `publish` field to Scarb.toml to mark package as not publishable to the registry

scarb/src/resolver/mod.rs
~2.7 <=> >=2.7.0 && < 2.8.0 which does not accept 2.9.0
=> Fix ignored test case

extensions/scarb-doc/src/docs_generation.rs, extensions/scarb-doc/src/docs_generation/markdown.rs, extensions/scarb-doc/src/docs_generation/markdown/book_toml.rs, extensions/scarb-doc/src/docs_generation/markdown/summary.rs, extensions/scarb-doc/src/main.rs
commit-id:a52783f6
---
**Stack**:
- #1464
- #1463 ⬅
=> Markdown generation

Cargo.lock, scarb/src/core/manifest/summary.rs, scarb/src/core/source/id.rs, scarb/src/internal/static_hash_cache.rs, scarb/src/lib.rs, scarb/src/version.rs, scarb/tests/build_cairo_plugin.rs, utils/scarb-test-support/Cargo.toml, utils/scarb-test-support/src/command.rs, utils/scarb-test-support/src/manifest_edit.rs, utils/scarb-test-support/src/registry/http.rs
- **Replace once_cell::sync::Lazy with std::sync::LazyLock**
- **Replace once_cell::sync::OnceCell with std::sync::OnceLock, unless used with get_or_try_init**
=> Replace stabilized once_cell api

extensions/scarb-doc/src/docs_generation/markdown/book_toml.rs, extensions/scarb-doc/tests/data/hello_world_no_features/book.toml, extensions/scarb-doc/tests/data/hello_world_sub_package_no_features/book.toml, extensions/scarb-doc/tests/data/hello_world_sub_package_with_features/book.toml, extensions/scarb-doc/tests/data/hello_world_sub_package_without_features/book.toml, extensions/scarb-doc/tests/data/hello_world_with_features/book.toml, extensions/scarb-doc/tests/data/hello_world_without_features/book.toml, extensions/scarb-doc/theme/CONTRIBUTING.md, extensions/scarb-doc/theme/highlight.js
fix #1565 
mdBook during the parsing, put's all the hidden lines (beggining with `#`) inside the `span` tag with `className="boring"`.
mdBook generated css files sets all the files with `boring` className to be `display: none`. Unfortunately, new version of `highlight.js` wipes all those mdBook spans during the highlighting process.
This version of `highlight.js` is based directly upon the mdBook `highlight.js`, so hidden lines work as intended inside rust codes examples.
=> Update highlight.js / hidden line rust.

CONTRIBUTING.md, xtask/src/set_cairo_version.rs
This small utility seems very helpful when setting up custom Scarb
checkout for testing some work on the Cairo compiler.
=> Add `cargo xtask set-cairo-version --path`

extensions/scarb-cairo-run/tests/arguments.rs, extensions/scarb-cairo-run/tests/build.rs, extensions/scarb-cairo-run/tests/examples.rs, extensions/scarb-cairo-test/tests/build.rs, scarb/src/ops/compile.rs, scarb/tests/build.rs, scarb/tests/build_cairo_plugin.rs, scarb/tests/build_starknet_contract.rs, scarb/tests/build_starknet_contract_allowed_libfuncs.rs, scarb/tests/build_starknet_external_contracts.rs, scarb/tests/build_targets.rs, scarb/tests/check.rs, scarb/tests/flock.rs, scarb/tests/git_source.rs, scarb/tests/local_registry.rs, scarb/tests/package.rs, scarb/tests/profiles.rs, scarb/tests/subcommand.rs, website/docs/guides/creating-a-new-package.md, website/docs/guides/dependencies.md, website/docs/guides/working-on-an-existing-package.md
- **Print profile name in finished targets message**
- **Update test asserts**
=> Print profile name in finished targets message

scarb/src/compiler/plugin/proc_macro/host.rs, scarb/tests/build_cairo_plugin.rs
=> Support more ModuleItems in proc macro attribute expansion

Cargo.lock, Cargo.toml, extensions/scarb-doc/src/types.rs, extensions/scarb-doc/tests/data/duplicated_item_names/src/hello_world-DuplicatedEnumName.md, extensions/scarb-doc/tests/data/duplicated_item_names/src/hello_world-sub_module-DuplicatedEnumName.md, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-Circle.md, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-Color.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-Circle.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-Color.md, extensions/scarb-doc/tests/data/json_output_test_data.json, extensions/scarb-doc/tests/data/json_private_items_excluded.json, extensions/scarb-doc/tests/data/json_private_items_included.json, extensions/scarb-doc/tests/data/json_reexports.json
Fixes [#1509](https://github.com/software-mansion/scarb/issues/1509). It waits for [this](https://github.com/starkware-libs/cairo/pull/6387) to be merged in Cairo.
=> Add signature for struct's member

scarb/src/bin/scarb/args.rs, scarb/src/bin/scarb/commands/fmt.rs, scarb/src/ops/fmt.rs, scarb/tests/fmt.rs
Allows formatting a single file. Useful for integration with external tools.
Closes #1534
=> feat: scarb fmt a subdirectory

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/compiler/plugin/proc_macro/compilation.rs, scarb/src/flock.rs, scarb/src/ops/package.rs, scarb/tests/package.rs
Resolves the issue brought up in https://github.com/software-mansion/scarb/pull/1605#discussion_r1795247757
=> Fix packaging plugins when `--no-verify` is passed

extensions/scarb-cairo-run/src/main.rs, extensions/scarb-doc/src/main.rs
commit-id:89f8cde3
---
**Stack**:
- #1668
- #1667 ⬅
=> Return ExitCode instead of process:exit() in extensions

.github/workflows/website-deploy.yml, website/.vitepress/config.mjs
Closes #1381
Preview: 
- https://delevoxdg.github.io/scarb/corelib/index.html
- https://delevoxdg.github.io/scarb/docs
=> Add `scarb-doc`-generated corelib docs to GitHub Pages

extensions/scarb-cairo-run/src/main.rs
This PR introduces an optional CLI parameter --print-detailed-resources for scarb cairo-run extension that prints detailed used resources report:
=> Feat: Support --print-detailed-resources parameter in cairo-run

scarb/src/ops/proc_macro_server/mod.rs
**Stack**:
- #1686
- #1685
- #1684
- #1683
- #1718
- #1682 ⬅
=> Add request handling

scarb/src/ops/proc_macro_server/methods/expand_attribute.rs, scarb/src/ops/proc_macro_server/methods/mod.rs, scarb/src/ops/proc_macro_server/mod.rs, scarb/tests/proc_macro_server.rs
**Stack**:
- #1686
- #1685
- #1684 ⬅
=> Add `ExpandAttribute` handler

Cargo.lock, plugins/cairo-lang-macro-stable/src/lib.rs, plugins/cairo-lang-macro/Cargo.toml, plugins/cairo-lang-macro/src/types/conversion.rs, plugins/cairo-lang-macro/src/types/mod.rs, plugins/cairo-lang-macro/src/types/token.rs, scarb/Cargo.toml, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/src/compiler/plugin/proc_macro/mod.rs, scarb/src/compiler/plugin/proc_macro/types.rs, scarb/src/ops/proc_macro_server/methods/expand_derive.rs, scarb/tests/build_cairo_plugin.rs, scarb/tests/proc_macro_server.rs, utils/scarb-test-support/src/proc_macro_server.rs
commit-id:ab3e2fd1
---
**Stack**:
- #1734
- #1722
- #1704
- #1700
- #1699 ⬅
=> Rework internal TokenStream representation

extensions/scarb-doc/src/docs_generation/markdown/traits.rs, scarb/src/core/checksum.rs, scarb/src/core/config.rs, scarb/src/core/registry/cache.rs, scarb/src/core/registry/client/http.rs, scarb/src/core/registry/patcher.rs, scarb/src/core/registry/source_map.rs, scarb/src/core/workspace.rs, scarb/src/internal/to_version.rs, scarb/src/ops/fmt.rs, scarb/src/process.rs, scarb/src/sources/git/mod.rs, scarb/src/sources/path.rs, scarb/src/sources/registry.rs, scarb/src/sources/standard_lib.rs, utils/scarb-test-support/src/project_builder.rs, utils/scarb-ui/src/args/packages_filter.rs, utils/scarb-ui/src/components/status.rs, utils/scarb-ui/src/components/typed.rs, utils/scarb-ui/src/components/value.rs
- **Clippy --fix**
- **Elided lifetime has a name**
=> Fix clippy warnings after rust update

Cargo.lock
as bytes 1.6.0 got yanked, bump it to 1.9.0
relates to https://github.com/Homebrew/homebrew-core/pull/199546
=> fix: bump bytes to 1.9.0

website/docs/extensions/documentation-generation.md
=> Add linkage docs to scarb doc

plugins/cairo-lang-macro/Cargo.toml, plugins/cairo-lang-macro/src/lib.rs, plugins/cairo-lang-macro/src/types/token.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host/attribute.rs, scarb/src/compiler/plugin/proc_macro/host/conversion.rs, scarb/src/compiler/plugin/proc_macro/host/derive.rs, scarb/src/compiler/plugin/proc_macro/host/inline.rs, scarb/src/compiler/plugin/proc_macro/host/mod.rs, scarb/src/ops/proc_macro_server/methods/expand_attribute.rs, scarb/src/ops/proc_macro_server/methods/expand_derive.rs, scarb/src/ops/proc_macro_server/methods/expand_inline.rs, scarb/tests/proc_macro_server.rs, utils/scarb-proc-macro-server-types/src/methods/expand.rs
commit-id:206643a1
---
**Stack**:
- #1811
- #1810
- #1749 ⬅
=> Pass call site to macro expansion

scarb/src/ops/package.rs, scarb/tests/package.rs, website/docs/reference/scripts.md, website/docs/registries/publishing.md
fixes #1771
commit-id:40843cae
---
**Stack**:
- #1846
- #1836 ⬅
=> AOT package script

scarb/src/compiler/compilers/executable.rs, scarb/src/compiler/compilers/lib.rs, scarb/src/compiler/compilers/mod.rs, scarb/src/compiler/compilers/starknet_contract/compiler.rs, scarb/src/compiler/compilers/test.rs, scarb/src/compiler/plugin/proc_macro/compilation.rs, scarb/src/compiler/repository.rs, scarb/src/core/manifest/target_kind.rs, scarb/tests/build_targets.rs
=> feat: compile executable

scarb/src/compiler/compilers/starknet_contract/compiler.rs, scarb/src/compiler/compilers/starknet_contract/contract_selector.rs, scarb/tests/build_starknet_external_contracts.rs
fix https://github.com/software-mansion/scarb/issues/1735
=> Support re-exported contracts in build-external

scarb-metadata/CHANGELOG.md, scarb-metadata/src/lib.rs, scarb/src/compiler/compilation_unit.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/src/core/package/mod.rs, scarb/src/core/resolver.rs, scarb/src/ops/metadata.rs, scarb/src/ops/resolve.rs, scarb/tests/metadata.rs
=> Add allowed prebuilts list

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/bin/scarb/commands/proc_macro_server.rs, scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/db.rs, scarb/src/compiler/plugin/mod.rs, scarb/src/compiler/plugin/proc_macro/compilation.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/src/ops/compile.rs, scarb/src/ops/expand.rs, scarb/src/ops/metadata.rs, scarb/src/ops/resolve.rs, scarb/tests/build_cairo_plugin.rs, scarb/tests/proc_macro_prebuilt.rs, scarb/tests/proc_macro_server.rs, utils/scarb-test-support/src/cairo_plugin_project_builder.rs, utils/scarb-test-support/src/proc_macro_server.rs
Originally submitted as https://github.com/software-mansion/scarb/pull/1812
=> Load prebuilt macros

scarb/src/resolver/algorithm/mod.rs, scarb/src/resolver/mod.rs, scarb/src/resolver/primitive.rs
commit-id:3ba8d8f0
---
**Stack**:
- #1453
- #1665
- #1452 ⬅
=> Refactor -> move simple resolver to separate mod

Cargo.lock, Cargo.toml, utils/once-map/Cargo.toml, utils/once-map/src/lib.rs
commit-id:293590d9
---
**Stack**:
- #1453
- #1665 ⬅
=> Add once_map package

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/core/lockfile.rs, scarb/src/core/registry/mod.rs, scarb/src/resolver/algorithm/in_memory_index.rs, scarb/src/resolver/algorithm/mod.rs, scarb/src/resolver/algorithm/provider.rs, scarb/src/resolver/algorithm/solution.rs, scarb/src/resolver/algorithm/state.rs, scarb/src/resolver/mod.rs, scarb/src/resolver/primitive.rs, scarb/tests/add.rs, scarb/tests/git_source_network.rs, scarb/tests/http_registry.rs, scarb/tests/local_registry.rs, scarb/tests/resolver_with_git.rs
=> PubGrub resolver

website/docs/guides/formatting.md
=> docs: update formatting

extensions/scarb-execute/tests/arguments.rs, extensions/scarb-execute/tests/build.rs, scarb/src/compiler/compilers/executable.rs, scarb/tests/build_targets.rs
commit-id:671bf5e1
replaces https://github.com/software-mansion/scarb/pull/1929
=> Require disabled gas in executable target compilation

scarb/src/sources/git/client.rs, scarb/tests/add.rs, utils/scarb-ui/src/args/verbosity.rs, utils/scarb-ui/src/lib.rs, utils/scarb-ui/src/verbosity.rs, website/docs/writing-extensions/subcommands.md
Add `no-warning` verbosity option, available as `--no-warning` flag or env var setting
Closes #1660
=> Allow hiding warnings in Scarb output

website/download.md
If you feel this PR is too minor, on the level of a simple typo fix, please don’t hesitate to close it.
That said, the `asdf` tool has introduced a few minor changes to its commands with the version 0.16.0 , and this PR updates the `Install via asdf` section in the download documentation accordingly. These adjustments ensure that anyone following the docs will use the correct commands and avoid potential errors as I did.
=> Update asdf usage instructions on the website/download page

.github/workflows/nightly.yml, Cargo.lock, Cargo.toml
- **Update cairo-toolchain-xtasks**
- **Update stwo-cairo rev**
- **Upgrade stwo-cairo when building nightly release**
=> Upgrade stwo-cairo when building nightly release

scarb/src/resolver/algorithm/provider.rs, scarb/src/resolver/algorithm/solution.rs, scarb/src/resolver/mod.rs, scarb/tests/add.rs, scarb/tests/git_source.rs, scarb/tests/git_source_network.rs, scarb/tests/http_registry.rs, scarb/tests/local_registry.rs
fixes #1883
When resolving package dependencies, the resolver accepts workspace lockfile (Scarb.lock) as one of the inputs. If manifest dependencies can be locked to concrete revisions defined in the lockfile (https://github.com/software-mansion/scarb/blob/52c5afe0e26c49e81b93d1b8929dc500a61495e5/scarb/src/core/lockfile.rs#L98) (i.e. unless the dependency conflicts with the locked version, for instance because the rev in dependency has been changed by the user between runs), it should be used by the resolver instead of the most recent one. 
This PR attempts to solve a bug in mechanism of applying locked revisions in the resolver. When querying the registry for dependency package summaries (https://github.com/software-mansion/scarb/blob/47c7c7d8dda31fccc4f63836027977e4ea0f28f4/scarb/src/res …
=> Pubgrub lockfile lookup fix

scarb-metadata/src/lib.rs, scarb/src/compiler/compilation_unit.rs, scarb/src/ops/metadata.rs, scarb/src/ops/resolve.rs
**Stack**:
- #1921
- #1913
- #1970
- #1920
- #1919
- #1890
- #1889 ⬅
=> Treat Cairo plugins as package dependencies

extensions/scarb-doc/src/metadata/compilation.rs
* `scarb-doc` properly analyzes the component dependencies obtained from metadata
=> Skip plugin dependencies in `scarb-doc`

scarb/src/compiler/compilers/starknet_contract/artifacts_writer.rs
=> Ignore `debug_info` when emitting file size warnings for contracts compilation

.github/workflows/ci.yml
This way we can build stable and nightly in parallel, instead of first waiting for stable to build and then building nightly. I suggest using nextest, even if we do not use partitioning, because it's well suited for archiving build and running from the archive.
=> Split nightly crates tests job to build and run steps

scarb/src/compiler/compilation_unit.rs, scarb/src/compiler/plugin/collection.rs, scarb/src/ops/proc_macro_server/methods/defined_macros.rs, scarb/src/ops/proc_macro_server/methods/expand_attribute.rs, scarb/src/ops/proc_macro_server/methods/expand_derive.rs, scarb/src/ops/proc_macro_server/methods/expand_inline.rs, scarb/tests/proc_macro_prebuilt.rs, scarb/tests/proc_macro_server.rs, utils/scarb-proc-macro-server-types/src/methods/defined_macros.rs, utils/scarb-proc-macro-server-types/src/scope.rs, utils/scarb-test-support/src/proc_macro_server.rs
* Proc Macro Server now identifies workspace packages using a `CompilationUnitComponent` type which wraps the name and discriminator of the Cairo package
* This new API abstracts the implementation details about the package ids and names and reduces the reliance on implicit contracts
=> Represent a package in Proc Macro Server more reliably

extensions/scarb-cairo-run/src/main.rs, extensions/scarb-cairo-test/src/main.rs, extensions/scarb-cairo-test/tests/build.rs, extensions/scarb-execute/src/lib.rs, extensions/scarb-execute/tests/build.rs, scarb-metadata/src/command/scarb_command.rs, scarb/tests/build_cairo_plugin.rs, utils/scarb-ui/src/components/mod.rs, utils/scarb-ui/src/components/new_line.rs, utils/scarb-ui/src/verbosity.rs
fixes #1923 
- **Use scarb-ui in cairo-test**
- **Propagate verbosity level when calling ScarbCommand**
=> Propagate ui verbosity when using scarbcommand in extensions

website/docs/reference/manifest.md, website/docs/reference/procedural-macro.md
fixes #2063 
- **Doc inlining strategy as weight parameter**
- **Add allow-prebuilt-plugins docs to manifest reference**
- **Document prebuilt macro plugins**
=> Add docs for prebuilt plugins and inlining strategy by weight

scarb/src/core/resolver.rs, scarb/src/ops/resolve.rs, scarb/tests/metadata.rs
fixes #2118
This problem is analog to the https://github.com/software-mansion/scarb/issues/1535 (https://github.com/software-mansion/scarb/pull/1542). 
If a package (A) that is a ws member depends on another ws member (B), and (B) depends on some cairo plugin (C) as dev dependency, test CompilationUnit of (A) will include (C) as dependency of (B), although dev dependencies of (B) should not be propagated to the test compilation of (A) (both Cairo and Plugin dependencies).   
- **Add failing test for propagation of dev dep plugins from members of ws**
- **Do not propagate plugins that are dev dependencies of ws members to packages that depend on these ws members**
=> Fix dev-deps propagation of compiler plugins for ws members

scarb/src/compiler/db.rs, scarb/src/core/manifest/compiler_config.rs, scarb/src/core/manifest/toml_manifest.rs, scarb/tests/build.rs, scarb/tests/metadata.rs, website/docs/reference/manifest.md
Related https://github.com/foundry-rs/starknet-foundry/issues/3070
This PR allows enabling `panic-backtrace`, which was added in [#7377](https://github.com/starkware-libs/cairo/pull/7377).  
This new hint is foundational for `forge backtrace` when handling panics in Cairo.
=> Add `panic-backtrace` flag

scarb/src/ops/proc_macro_server/methods/expand_derive.rs, scarb/tests/proc_macro_v1_and_v2_server.rs
It was added on LS side, but was never actually used since the v1 and v2 macros can be expanded in tandem, this would always return an empty vector instead of `None`, thus the default mapping could not be constructed
=> Restore default mapping for v1 derives on expansion

scarb/src/ops/proc_macro_server/methods/defined_macros.rs, utils/scarb-proc-macro-server-types/src/methods/defined_macros.rs
* `DefinedMacrosResponse` from `proc-macro-server-types` contains an additional field `debug_info: DebugInfo`.
* `DebugInfo` contains a field `source_packages` which informs about the proc macro packages loaded by the server.
=> Inform about the source packages for proc macros in PMS

scarb/src/compiler/plugin/collection.rs, scarb/src/compiler/plugin/proc_macro/expansion.rs, scarb/src/compiler/plugin/proc_macro/host.rs, scarb/src/compiler/plugin/proc_macro/instance.rs, scarb/src/compiler/plugin/proc_macro/v1/ffi.rs, scarb/src/compiler/plugin/proc_macro/v1/host.rs, scarb/src/compiler/plugin/proc_macro/v2/ffi.rs, scarb/src/compiler/plugin/proc_macro/v2/host/attribute.rs, scarb/src/compiler/plugin/proc_macro/v2/host/derive.rs, scarb/src/compiler/plugin/proc_macro/v2/host/inline.rs, scarb/src/compiler/plugin/proc_macro/v2/host/mod.rs, scarb/src/ops/proc_macro_server/methods/expand_attribute.rs, scarb/src/ops/proc_macro_server/methods/expand_derive.rs, scarb/src/ops/proc_macro_server/methods/expand_inline.rs, scarb/tests/proc_macro_v2_expand.rs
- **Add test case**
- **Fix casing in derive macro lookup**
=> Fix casing in derive macro lookup

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/compiler/plugin/proc_macro/expansion.rs, scarb/src/compiler/plugin/proc_macro/v1/host.rs, scarb/src/compiler/plugin/proc_macro/v2/host/aux_data.rs, scarb/src/compiler/plugin/proc_macro/v2/host/conversion.rs, scarb/src/compiler/plugin/proc_macro/v2/host/mod.rs, scarb/src/compiler/plugin/proc_macro/v2/types.rs, scarb/src/ops/expand.rs, scarb/src/ops/scripts.rs, scarb/src/sources/git/client.rs
* `cairo-lang-*`, `cairo-language-server` and `cairo-lint` are set to latest revisions
* `impl GeneratedFileAuxData for EmittedAuxData` for both macro APIs are marked with `typetag::serde` because the compiler requires it
* `Cargo.lock` has been regenerated because of some conflicts between `cairo-lint` and `stwo-*` which implies slight changes in versions of some dependencies ->
* -> `ops::scripts::execute_script` is adjusted to the requirements of newer `deno` runner
=> Upgrade Cairo, LS and Lint

.github/workflows/nightly.yml
Docs: https://cli.github.com/manual/gh_release_create
"Mark this release as "Latest" (default [automatic based on date and version]). --latest=false to explicitly NOT set as latest"
=> Fix nightly/dev upload setting latest flag

extensions/scarb-doc/src/docs_generation.rs, extensions/scarb-doc/src/docs_generation/markdown/context.rs, extensions/scarb-doc/src/docs_generation/markdown/summary.rs, extensions/scarb-doc/src/docs_generation/markdown/traits.rs, extensions/scarb-doc/tests/code/code_6.cairo, extensions/scarb-doc/tests/data/hello_world_linked_items/book.toml, extensions/scarb-doc/tests/data/hello_world_linked_items/src/SUMMARY.md, extensions/scarb-doc/tests/data/hello_world_linked_items/src/hello_world-Congo.md, extensions/scarb-doc/tests/data/hello_world_linked_items/src/hello_world-CongoUganda.md, extensions/scarb-doc/tests/data/hello_world_linked_items/src/hello_world-Guinea.md, extensions/scarb-doc/tests/data/hello_world_linked_items/src/hello_world-Uganda.md, extensions/scarb-doc/tests/data/hello_world_linked_items/src/hello_world-enums.md, extensions/scarb-doc/tests/data/hello_world_linked_items/src/hello_world-impls.md, extensions/scarb-doc/tests/data/hello_world_linked_items/src/hello_world-structs.md, extensions/scarb-doc/tests/data/hello_world_linked_items/src/hello_world-traits.md, extensions/scarb-doc/tests/data/hello_world_linked_items/src/hello_world.md, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-Circle.md, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-CirclePartialEq.md, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-CircleSerde.md, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-CircleShape.md, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-Color.md, extensions/scarb-doc/tests/data/hello_world_no_features/src/hello_world-Shape.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-Circle.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-CirclePartialEq.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-CircleSerde.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-CircleShape.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-Color.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-Shape.md, extensions/scarb-doc/tests/markdown_links.rs
closes https://github.com/software-mansion/scarb/issues/2129
- When linked item cannot be successfully connected with any _DocumentableItemId_ scarb-doc will not format it as a link but as a regular text.
- fix _Fully qualified path_ for _Variant_ and _Member_.
=> fix: linking doc items

scarb/src/compiler/plugin/builtin.rs, scarb/src/compiler/plugin/collection.rs, scarb/src/compiler/plugin/mod.rs, scarb/tests/proc_macro_v2_build.rs
Expanding a proc macro attribute on a function creates a virtual file with the expanded implementation and removes the old node. The executable plugin generates a new function - wrapper, which calls the original one. If we run executable plugin before proc macros, using a proc macro attribute on executable function would cause it to be duplicated (and thus fail with error).
=> Run proc macro expansion before executable plugin

extensions/scarb-doc/src/docs_generation/markdown/summary.rs, extensions/scarb-doc/src/docs_generation/markdown/traits.rs, extensions/scarb-doc/src/lib.rs, extensions/scarb-doc/src/types.rs, extensions/scarb-doc/tests/data/json_doc_hidden.json, extensions/scarb-doc/tests/data/json_doc_hidden_impls.json, extensions/scarb-doc/tests/data/json_output_test_data.json, extensions/scarb-doc/tests/data/json_private_items_excluded.json, extensions/scarb-doc/tests/data/json_private_items_included.json, extensions/scarb-doc/tests/data/json_reexports.json
closes https://github.com/software-mansion/scarb/issues/2161
The idea is to document all reexported items and create pages for all their parents if they don't exist using original path not the reexported one. 
So the expected behaviour is that for example (comes from corelib) for `pub use adapters::PeekableTrait;` gets documented in path` core-iter-adapters-peekable-PeekableTrait` and only there. 
Before the change each _pub use_ of the same item would be documented in `SUMMARY.md` causing the `mdbook build` to fail. 
To reproduce this bug you can pull scarb repo (from before this PR gets merged) generate documentation for corelib or any other package that contains more than one pub use for the same item and run `mdbook build`. 
New interface sample 👇
=> ref: document pub uses

extensions/scarb-doc/src/types.rs, extensions/scarb-doc/tests/data/json_reexports_merged_module.json, extensions/scarb-doc/tests/reexports.rs
following change for https://github.com/software-mansion/scarb/pull/2216
fixes modules overriding itself when reexported multiple times. 
see example in `test_reexports_merged_modules` 👉 `hello_world::Rodrigo::Valentina` wouldn't be documented.
=> feat: merge modules

extensions/scarb-execute/src/lib.rs, extensions/scarb-prove/src/main.rs, utils/scarb-extensions-cli/src/execute.rs
`scarb execute` creates new output folder `target/execute/execution{i}` for every new invocation. When used for integration tests this causes rapid disk space bloat.
This PR introduces a new option `--output none` that suppresses creating new directoris and skips writing artifacts.
=> Execution args: allow to suppress execution output

extensions/scarb-cairo-run/tests/arguments.rs, extensions/scarb-cairo-run/tests/build.rs, extensions/scarb-cairo-run/tests/examples.rs, extensions/scarb-cairo-test/tests/build.rs, extensions/scarb-doc/tests/diagnostics.rs, extensions/scarb-doc/tests/features.rs, extensions/scarb-execute/tests/build.rs, extensions/scarb-prove/tests/build.rs, extensions/scarb-verify/tests/build.rs, scarb/src/bin/scarb/main.rs, scarb/src/ops/subcommands.rs, scarb/src/process.rs, utils/scarb-test-support/src/command.rs
This PR reimplements our `exec_replace` approach to fix two issues:
1. We have inconsistently added a `error: process did not exit successfully: exit code: 1` line only on Windows, and this was accounted for in tests in a very dirty way.
2. We never cared about destructing objects created up in the call stack. This PR actually fixes an unnoticed bug - calling `exec_replace` would result in broken (unterminated) trace files.
=> reimplement `exec_replace`

extensions/scarb-execute/src/oracle/jsonrpc.rs, extensions/scarb-execute/src/oracle/mod.rs
It is surprising how complex existing JSON-RPC Rust implementations are, we don't need any kinds of async, extendibility or network stuff that they provide.
=> add minimal JSON-RPC types implementation

Cargo.lock, Cargo.toml, extensions/scarb-execute/Cargo.toml, extensions/scarb-execute/src/lib.rs, extensions/scarb-execute/src/output.rs
This PR adds several extra fields that are useful for benchmarking:
- Memory segments size
- Max memory segment address
Also formatting is changed to improve readability:
- One property per line (easier to calculate diff)
- Colored values, thousand separators
=> scarb-execute: extend resource info with memory segments & improve formatting

scarb/src/compiler/plugin/proc_macro/v2/host/attribute/inner_attribute.rs, scarb/src/compiler/plugin/proc_macro/v2/host/attribute/item_attribute.rs, scarb/src/compiler/plugin/proc_macro/v2/host/attribute/parse_attributes.rs, scarb/src/compiler/plugin/proc_macro/v2/host/attribute/span_adapter.rs, scarb/tests/proc_macro_v2_expand.rs, utils/scarb-test-support/src/cairo_plugin_project_builder.rs
- **Use 2.12.0-rc.2 parser in proc macro tests**
- **Pass whole token stream span to the span adapter**
- ** Rewrite token stream spans to start at zero**
This has to be done, as get_text method in the compiler now works by slicing the file content with the spans, so we cannot start the parser with non-zero initial offset for new virtual files with token content only.
=> Rewrite token stream spans to start at zero, for optimized get_text method

Cargo.lock, Cargo.toml, scarb/Cargo.toml, scarb/src/core/registry/client/cache.rs, scarb/src/core/registry/client/http.rs, scarb/src/core/registry/client/local.rs, scarb/src/core/registry/client/mod.rs, scarb/src/core/registry/package_source_store.rs, scarb/src/flock.rs, scarb/src/ops/lockfile.rs, scarb/src/ops/package.rs, scarb/src/sources/registry.rs
1. Rust 1.89.0 brought all features that we used from fs4 into std 🎉
2. It turns out we don't have to explicitly unlock files because they are going to already be unlocked then the file is closed - which happens when we drop guards.
3. Renamed `(Async)FileLockGuard` to `(Async)LockedFile` because it's better naming now
=> Refactor file lock guards

.github/workflows/nightly.yml
Problem: 
`dev-` tags are not fetched
Solution: 
add [--paginate](https://cli.github.com/manual/gh_api#:~:text=for%20the%20request-,%2D%2Dpaginate,-Make%20additional%20HTTP) flag to fetch all pages
=> fix: get all matching tags

scarb/src/compiler/incremental/fingerprint.rs, scarb/src/compiler/plugin/collection.rs, scarb/src/compiler/plugin/proc_macro/ffi.rs, scarb/src/compiler/plugin/proc_macro/mod.rs, scarb/tests/incremental.rs
Move proc macro repository access to a trait
Use macro defined fingerprint in digest calculation
Add a test case
=> Use macro defined fingerprint in digest calculation

scarb/src/compiler/incremental/compilation.rs, scarb/src/compiler/incremental/fingerprint.rs
Do not create cache file, until cache is ready
Write cache fingerprint file after the cache itself
Lock cache file before reading
Add cu component name to cache traces
=> Make incremental cache file handling more defensive

extensions/scarb-doc/src/docs_generation/markdown.rs, extensions/scarb-doc/tests/data/hello_world_sub_package_no_features/src/hello_world-sub_package-free_functions.md, extensions/scarb-doc/tests/data/hello_world_sub_package_no_features/src/hello_world_sub_package.md, extensions/scarb-doc/tests/data/hello_world_sub_package_with_features/src/hello_world-sub_package-free_functions.md, extensions/scarb-doc/tests/data/hello_world_sub_package_with_features/src/hello_world_sub_package.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world-free_functions.md, extensions/scarb-doc/tests/data/hello_world_with_features/src/hello_world.md, website/docs/extensions/documentation-generation.md
closes https://github.com/software-mansion/scarb/issues/2536
`pulldown_cmark` does not recognise file embedding md markers, however it does work out of the box because it is interpreted correctly by mdbook, so basically no changes are required for it to work
implemented changes & why:
- the marker is added to the `SHORT_DOCUMENTATION_AVOID_PREFIXES` to avoid weird formatting results in the doc summarising (tables) webpage 
-  also, I did change the ```\n prefix, it was useless as the language is always enforced by [parser](https://github.com/starkware-libs/cairo/blob/53bec47f3938a7b732489856cdffe67b6f2c0a79/crates/cairo-lang-doc/src/parser.rs#L192)
- doc: I think it can be useful to specify the officialy supported mdbook syntax, let me know if you don't agree or have different idea 🙏 
- …
```
=> feat: minor adjustment file embeding support in scarb doc, update docs

scarb/tests/git_source_network.rs
Getting tired of failed runs, I don't think it makes sense to keep running this test on windows
=> Ignore flaky https_something_happens on windows runners

scarb/src/core/manifest/summary.rs, scarb/src/core/registry/source_map.rs, scarb/src/core/source/id.rs, scarb/src/ops/resolve.rs, scarb/src/resolver/mod.rs, scarb/src/resolver/provider.rs, scarb/src/sources/registry.rs, scarb/tests/yanked.rs
Use the same approach as applied to audit status filtering in #2561
- #2560
- #2561
- #2617
- #2563
- #2562 
- #2566
- #2575
- #2576
=> Refactor yanked version filtering in line with audit filtering

scarb/tests/audits.rs, scarb/tests/local_registry.rs
Adds test for `scarb update`:
- in regular context (no such test was present for registry deps)
- in audits context
- #2560
- #2561
- #2617
- #2563
- #2562 
- #2566
- #2575
- #2576
=> Test `scarb update` in audit and regular context

Cargo.lock, scarb/Cargo.toml, scarb/src/compiler/compilers/executable.rs, scarb/src/compiler/compilers/lib.rs, scarb/src/compiler/compilers/starknet_contract/compiler.rs, scarb/src/compiler/compilers/test.rs, scarb/src/compiler/helpers.rs, scarb/src/compiler/incremental/compilation.rs, scarb/src/compiler/incremental/mod.rs, scarb/src/compiler/mod.rs, scarb/src/compiler/repository.rs, scarb/src/ops/compile.rs, scarb/src/ops/expand.rs
This way we can skip calculating diagnostics for main crates.
=> Save information about warnings in cache
